/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Conexao.ConexaoBD;
import ModeloBeans.BeansCadProdutos;
import ModeloDao.DaoCadProdutos;
import ModeloDao.PreencherTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Jhonny_Queillia
 */
public class CadastroProdutos extends javax.swing.JDialog {
    ConexaoBD conecta = new ConexaoBD();
    BeansCadProdutos mod = new BeansCadProdutos();
    DaoCadProdutos dao =  new DaoCadProdutos();
    int flag = 0;

    /**
     * Creates new form CadastroProdutos
     */
    public CadastroProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        preencherTabela("select *from produtos order by descricao_produto");
        preencherFornecedores();
        preencherCategoria();
    }

    CadastroProdutos() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabelPesquisarCliente = new javax.swing.JLabel();
        jTextFieldPesquisaCliente = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldFabricante = new javax.swing.JTextField();
        jLabelDataCadastro = new javax.swing.JLabel();
        jLabelCategoria = new javax.swing.JLabel();
        jLabelIDProduto = new javax.swing.JLabel();
        jTextFieldIDProduto = new javax.swing.JTextField();
        jLabelDescrição = new javax.swing.JLabel();
        jTextFieldDescrição = new javax.swing.JTextField();
        jLabelFabricante = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabelUnidade = new javax.swing.JLabel();
        jTextFieldUnidade = new javax.swing.JTextField();
        jTextFieldDataCadastro = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");
            jTextFieldDataCadastro = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelPrecoCusto = new javax.swing.JLabel();
        jTextFieldPrecoCusto = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter precocusto= new javax.swing.text.MaskFormatter("###.###,##");
            jTextFieldPrecoCusto = new javax.swing.JFormattedTextField(precocusto);
        }
        catch (Exception e){
        }
        jLabelPrecoVenda = new javax.swing.JLabel();
        jTextFieldPrecoVenda = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter precovenda= new javax.swing.text.MaskFormatter("###.###,##");
            jTextFieldPrecoVenda = new javax.swing.JFormattedTextField(precovenda);
        }
        catch (Exception e){
        }
        jLabelEstado = new javax.swing.JLabel();
        jTextFieldQtdeAtual = new javax.swing.JTextField();
        jLabelCEP = new javax.swing.JLabel();
        jTextFieldQtdeMinima = new javax.swing.JTextField();
        jLabelIDFornecedor = new javax.swing.JLabel();
        jTextFieldIDFornecedor = new javax.swing.JTextField();
        jLabelFornecedor = new javax.swing.JLabel();
        jComboBoxFornecedor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO DE PRODUTOS");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPesquisarCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPesquisarCliente.setForeground(new java.awt.Color(102, 102, 255));
        jLabelPesquisarCliente.setText("Pesquisar Cliente");

        jTextFieldPesquisaCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldPesquisaCliente.setForeground(new java.awt.Color(102, 102, 255));

        jButtonPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPesquisar.setForeground(new java.awt.Color(102, 102, 255));
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jTableProdutos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableProdutos.setForeground(new java.awt.Color(102, 102, 255));
        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableProdutos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelPesquisarCliente)
                        .addGap(223, 223, 223)
                        .addComponent(jTextFieldPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jLabelPesquisarCliente)
                    .addComponent(jTextFieldPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldFabricante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldFabricante.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldFabricante.setEnabled(false);

        jLabelDataCadastro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDataCadastro.setForeground(new java.awt.Color(102, 102, 255));
        jLabelDataCadastro.setText("Data de Cadastro");

        jLabelCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCategoria.setForeground(new java.awt.Color(102, 102, 255));
        jLabelCategoria.setText("Categoria");

        jLabelIDProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelIDProduto.setForeground(new java.awt.Color(102, 102, 255));
        jLabelIDProduto.setText("ID");

        jTextFieldIDProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldIDProduto.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldIDProduto.setEnabled(false);

        jLabelDescrição.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDescrição.setForeground(new java.awt.Color(102, 102, 255));
        jLabelDescrição.setText("Descrição");

        jTextFieldDescrição.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldDescrição.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldDescrição.setEnabled(false);

        jLabelFabricante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelFabricante.setForeground(new java.awt.Color(102, 102, 255));
        jLabelFabricante.setText("Fabricante");

        jComboBoxCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxCategoria.setForeground(new java.awt.Color(102, 102, 255));
        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Processador", "Placa de Video", " " }));
        jComboBoxCategoria.setEnabled(false);

        jLabelUnidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelUnidade.setForeground(new java.awt.Color(102, 102, 255));
        jLabelUnidade.setText("Unidade");

        jTextFieldUnidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldUnidade.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldUnidade.setEnabled(false);

        jTextFieldDataCadastro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldDataCadastro.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldDataCadastro.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelFabricante)
                    .addComponent(jLabelDescrição)
                    .addComponent(jLabelIDProduto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldDescrição)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldIDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelDataCadastro)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCategoria)
                    .addComponent(jLabelUnidade))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIDProduto)
                    .addComponent(jTextFieldIDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataCadastro)
                    .addComponent(jTextFieldDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescrição)
                    .addComponent(jTextFieldDescrição, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUnidade)
                    .addComponent(jTextFieldUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFabricante)
                    .addComponent(jTextFieldFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCategoria)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNovo.setForeground(new java.awt.Color(102, 102, 255));
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(102, 102, 255));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(102, 102, 255));
        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(102, 102, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluir.setForeground(new java.awt.Color(102, 102, 255));
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPrecoCusto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPrecoCusto.setForeground(new java.awt.Color(102, 102, 255));
        jLabelPrecoCusto.setText("Preço Custo");

        jTextFieldPrecoCusto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldPrecoCusto.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldPrecoCusto.setEnabled(false);

        jLabelPrecoVenda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPrecoVenda.setForeground(new java.awt.Color(102, 102, 255));
        jLabelPrecoVenda.setText("Preço Venda");

        jTextFieldPrecoVenda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldPrecoVenda.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldPrecoVenda.setEnabled(false);

        jLabelEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelEstado.setForeground(new java.awt.Color(102, 102, 255));
        jLabelEstado.setText("Qtde Atual");

        jTextFieldQtdeAtual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldQtdeAtual.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldQtdeAtual.setEnabled(false);

        jLabelCEP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCEP.setForeground(new java.awt.Color(102, 102, 255));
        jLabelCEP.setText("Qtde Minima");

        jTextFieldQtdeMinima.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldQtdeMinima.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldQtdeMinima.setEnabled(false);

        jLabelIDFornecedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelIDFornecedor.setForeground(new java.awt.Color(102, 102, 255));
        jLabelIDFornecedor.setText("ID ");

        jTextFieldIDFornecedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldIDFornecedor.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldIDFornecedor.setEnabled(false);

        jLabelFornecedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelFornecedor.setForeground(new java.awt.Color(102, 102, 255));
        jLabelFornecedor.setText("Fornecedor");

        jComboBoxFornecedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxFornecedor.setForeground(new java.awt.Color(102, 102, 255));
        jComboBoxFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxFornecedor.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPrecoCusto)
                    .addComponent(jLabelPrecoVenda)
                    .addComponent(jLabelIDFornecedor))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPrecoVenda)
                            .addComponent(jTextFieldPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEstado, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCEP, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldIDFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jLabelFornecedor)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldQtdeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldQtdeAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrecoCusto)
                    .addComponent(jTextFieldPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstado)
                    .addComponent(jTextFieldQtdeAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrecoVenda)
                    .addComponent(jLabelCEP)
                    .addComponent(jTextFieldQtdeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIDFornecedor)
                    .addComponent(jTextFieldIDFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFornecedor)
                    .addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonNovo)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExcluir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void preencherFornecedores() {
        conecta.conexao();
        conecta.executaSQL("select *from fornecedores order by razaosocial_fornecedor");
        try {
            conecta.rs.first();
            jComboBoxFornecedor.removeAllItems();
            do{
                jComboBoxFornecedor.addItem(conecta.rs.getString("razaosocial_fornecedor"));                
            }while(conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher a lista de fornecedores!"+ex);
        }
        
        conecta.desconexao();
    
    }
    
    public void preencherCategoria() {
        conecta.conexao();
        conecta.executaSQL("select *from categorias order by nome_categoria");
        try {
            conecta.rs.first();
            jComboBoxCategoria.removeAllItems();
            do{
                jComboBoxCategoria.addItem(conecta.rs.getString("nome_categoria"));                
            }while(conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher a lista de categorias!"+ex);
        }
        
        conecta.desconexao();
    
    }
    
    /*public void preencherIDFornecedores() {
        conecta.conexao();
        conecta.executaSQL("select *from fornecedores order by id_fornecedor");
        try {
            conecta.rs.first();
            jTextFieldIDFornecedor.setText(String.valueOf(conecta.rs.getString("id_fornecedor_produto")));    
                        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher a lista de fornecedores!"+ex);
        }
        
        conecta.desconexao();
    
    }*/
    
    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        mod.setPesquisar(jTextFieldPesquisaCliente.getText());
        BeansCadProdutos model = dao.Buscaproduto(mod);
        jTextFieldIDProduto.setText(String.valueOf(model.getIDProduto()));
        jTextFieldDataCadastro.setText(model.getDataCadastro());
        jTextFieldDescrição.setText(model.getDescricao());
        jTextFieldUnidade.setText(model.getUnidade());
        jTextFieldFabricante.setText(model.getFabricante());
        jComboBoxCategoria.setSelectedItem(model.getCategoria());
        jTextFieldPrecoCusto.setText(String.valueOf(model.getPrecoCusto()));
        jTextFieldPrecoVenda.setText(String.valueOf(model.getPrecoVenda()));
        jTextFieldQtdeAtual.setText(String.valueOf(model.getQtdeAtual()));
        jTextFieldQtdeMinima.setText(String.valueOf(model.getQtdeMinima()));
        jTextFieldIDFornecedor.setText(String.valueOf(model.getIDFornecedor()));
        jComboBoxFornecedor.setSelectedItem(model.getFornecedor());        

        jTextFieldPesquisaCliente.setText("");

        jButtonNovo.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        //jButtonPesquisar.setEnabled(false);
        preencherTabela("select *from produtos where descricao_produto like'%"+mod.getPesquisar()+"%'");
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutosMouseClicked
        String descricao_produto = "" + jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 2);
        conecta.conexao();
        conecta.executaSQL("select *from produtos where descricao_produto = '"+ descricao_produto + "'");
        try {
            conecta.rs.first();
            jTextFieldIDProduto.setText(String.valueOf(conecta.rs.getInt("id_produto")));
            jTextFieldDataCadastro.setText(conecta.rs.getString("datacadastro_produto"));
            jTextFieldDescrição.setText(conecta.rs.getString("descricao_produto"));
            jTextFieldUnidade.setText(conecta.rs.getString("unidade_produto"));
            jTextFieldFabricante.setText(conecta.rs.getString("fabricante_produto"));
            jComboBoxCategoria.setSelectedItem(conecta.rs.getString("categoria_produto"));
            jTextFieldPrecoCusto.setText(String.valueOf(conecta.rs.getFloat("precocusto_produto")));
            jTextFieldPrecoVenda.setText(String.valueOf(conecta.rs.getFloat("precovenda_produto")));
            jTextFieldQtdeAtual.setText(String.valueOf(conecta.rs.getInt("qtdeatual_produto")));
            jTextFieldQtdeMinima.setText(String.valueOf(conecta.rs.getInt("qtdeminima_produto")));
            jTextFieldIDFornecedor.setText(String.valueOf(conecta.rs.getInt("id_fornecedor_produto")));
            jComboBoxFornecedor.setSelectedItem(conecta.rs.getString("fornecedor_produto"));

        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar item!"+ex);
        }
        jButtonNovo.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonCancelar.setEnabled(false);
        jButtonExcluir.setEnabled(true);
        jButtonPesquisar.setEnabled(false);
        //jTableClientes.setEnabled(false);
        jTableProdutos.setVisible(false);

        jTextFieldPesquisaCliente.setText("");

        conecta.desconexao();

    }//GEN-LAST:event_jTableProdutosMouseClicked

    public void preencherTabela(String Sql) {
        ArrayList dados = new ArrayList();
        String [] colunas = new String [] {"ID","Data de Cadastro","Descrição","Unidade","Fabricante","Categoria","Preço de Custo","Preço de Venda","Qtd Atual","Qtd Minima","ID Forn.","Fornecedor",};
        conecta.conexao();
        conecta.executaSQL(Sql);
        
        try{
            conecta.rs.first();
            do{
                dados.add(new Object[] {conecta.rs.getInt("id_produto"),conecta.rs.getString("datacadastro_produto"),conecta.rs.getString("descricao_produto"),conecta.rs.getString("unidade_produto"),conecta.rs.getString("fabricante_produto"),conecta.rs.getString("categoria_produto"),conecta.rs.getFloat("precocusto_produto"),conecta.rs.getFloat("precovenda_produto"),conecta.rs.getInt("qtdeatual_produto"),conecta.rs.getInt("qtdeminima_produto"),conecta.rs.getInt("id_fornecedor_produto"),conecta.rs.getString("fornecedor_produto")});                
            }while(conecta.rs.next());                    
        }catch(SQLException ex) {
            
// Preenchendo a tabela
            JOptionPane.showMessageDialog(rootPane, "Faça uma nova busca, pois os dados pesquisados não existem!");
        }
        PreencherTabela modelo = new PreencherTabela(dados, colunas);
        
        jTableProdutos.setModel(modelo);        
        jTableProdutos.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableProdutos.getColumnModel().getColumn(0).setResizable(false);
        
        jTableProdutos.getColumnModel().getColumn(1).setPreferredWidth(120);
        jTableProdutos.getColumnModel().getColumn(1).setResizable(false);
        
        jTableProdutos.getColumnModel().getColumn(2).setPreferredWidth(240);
        jTableProdutos.getColumnModel().getColumn(2).setResizable(false);
        
        jTableProdutos.getColumnModel().getColumn(3).setPreferredWidth(60);
        jTableProdutos.getColumnModel().getColumn(3).setResizable(false);
        
        jTableProdutos.getColumnModel().getColumn(4).setPreferredWidth(160);
        jTableProdutos.getColumnModel().getColumn(4).setResizable(false);
        
        jTableProdutos.getColumnModel().getColumn(5).setPreferredWidth(160);
        jTableProdutos.getColumnModel().getColumn(5).setResizable(false);
        
        jTableProdutos.getColumnModel().getColumn(6).setPreferredWidth(100);
        jTableProdutos.getColumnModel().getColumn(6).setResizable(false);
        
        jTableProdutos.getColumnModel().getColumn(7).setPreferredWidth(100);
        jTableProdutos.getColumnModel().getColumn(7).setResizable(false);
        
        jTableProdutos.getColumnModel().getColumn(8).setPreferredWidth(80);
        jTableProdutos.getColumnModel().getColumn(8).setResizable(false);
        
        jTableProdutos.getColumnModel().getColumn(9).setPreferredWidth(80);
        jTableProdutos.getColumnModel().getColumn(9).setResizable(false);
        
        jTableProdutos.getColumnModel().getColumn(10).setPreferredWidth(40);
        jTableProdutos.getColumnModel().getColumn(10).setResizable(false);
        
        jTableProdutos.getColumnModel().getColumn(11).setPreferredWidth(280);
        jTableProdutos.getColumnModel().getColumn(11).setResizable(false);
        
        jTableProdutos.getTableHeader().setReorderingAllowed(false);
        jTableProdutos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTableProdutos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);      
        
        conecta.desconexao();
        
    }                        
    
    
    
    
    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;

        jTextFieldDataCadastro.setEnabled(true);
        jTextFieldDescrição.setEnabled(true);
        jTextFieldUnidade.setEnabled(true);
        jTextFieldFabricante.setEnabled(true);
        jComboBoxCategoria.setEnabled(true);
        jTextFieldPrecoCusto.setEnabled(true);
        jTextFieldPrecoVenda.setEnabled(true);
        jTextFieldQtdeAtual.setEnabled(true);
        jTextFieldQtdeMinima.setEnabled(true);
        jTextFieldIDFornecedor.setEnabled(true);
        jComboBoxFornecedor.setEnabled(true);              
        jTextFieldPesquisaCliente.setEnabled(false);

        jTextFieldIDProduto.setText("");
        jTextFieldDataCadastro.setText("");
        jTextFieldDescrição.setText("");
        jTextFieldUnidade.setText("");
        jTextFieldFabricante.setText("");        
        jTextFieldPrecoCusto.setText("");
        jTextFieldPrecoVenda.setText("");
        jTextFieldQtdeAtual.setText("");
        jTextFieldQtdeMinima.setText("");        
        jTextFieldIDFornecedor.setText("");       
        jTextFieldPesquisaCliente.setText("");

        jButtonNovo.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jButtonPesquisar.setEnabled(false);

    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if(jTextFieldDataCadastro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo DATA DE CADASTRO para prosseguir");
            jTextFieldDataCadastro.requestFocus();
        }else if (jTextFieldDescrição.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo DESCRIÇÃO para prosseguir");
            jTextFieldDescrição.requestFocus();
        }else if (jTextFieldUnidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo UNIDADE para prosseguir");
            jTextFieldUnidade.requestFocus();               
        }else if (jTextFieldFabricante.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo FABRICANTE para prosseguir");
            jLabelFabricante.requestFocus();
        /*}else if (jTextFieldNumero.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo NÚMERO para prosseguir");
            jTextFieldNumero.requestFocus();*/
        }else if (jTextFieldPrecoCusto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo PREÇO DE CUSTO para prosseguir");
            jTextFieldPrecoCusto.requestFocus();
        }else if (jTextFieldPrecoVenda.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo PREÇO DE VENDA para prosseguir");
            jTextFieldPrecoVenda.requestFocus();    
        }else if (jTextFieldQtdeAtual.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo QUANTIDADE ATUAL para prosseguir");
            jTextFieldQtdeAtual.requestFocus();
        }else if (jTextFieldQtdeMinima.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo QUANTIDADE MINIMA para prosseguir");
            jTextFieldQtdeMinima.requestFocus();
        }else if (jTextFieldIDFornecedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo ID DO FORNECEDOR para prosseguir");
            jTextFieldIDFornecedor.requestFocus();
        /*}else if (jComboBoxForncedor.getSelectedItem().removeAllItems()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo TELEFONE para prosseguir");
            jTextFieldUnidade.requestFocus();   */

        }else

        // FUNÇÃO INSERIR DADOS

        if(flag==1) {
            
            mod.setDataCadastro(jTextFieldDataCadastro.getText());
            mod.setDescricao(jTextFieldDescrição.getText());
            mod.setUnidade(jTextFieldUnidade.getText());
            mod.setFabricante(jTextFieldFabricante.getText());
            mod.setCategoria((String)(jComboBoxCategoria.getSelectedItem()));
            mod.setPrecoCusto(Float.valueOf(jTextFieldPrecoCusto.getText()));
            mod.setPrecoVenda(Float.valueOf(jTextFieldPrecoVenda.getText()));
            mod.setQtdeAtual(Integer.parseInt(jTextFieldQtdeAtual.getText()));
            mod.setQtdeMinima(Integer.parseInt(jTextFieldQtdeMinima.getText()));            
            mod.setIDFornecedor(Integer.parseInt(jTextFieldIDFornecedor.getText()));
            mod.setFornecedor((String)(jComboBoxFornecedor.getSelectedItem()));            
            dao.Salvar(mod);

                jTextFieldIDProduto.setText("");
                jTextFieldDataCadastro.setText("");
                jTextFieldDescrição.setText("");
                jTextFieldUnidade.setText("");
                jTextFieldFabricante.setText("");                
                jTextFieldPrecoCusto.setText("");
                jTextFieldPrecoVenda.setText("");
                jTextFieldQtdeAtual.setText("");
                jTextFieldQtdeMinima.setText("");                
                jTextFieldIDFornecedor.setText("");
                
                jTextFieldIDProduto.setEnabled(false);
                jTextFieldDataCadastro.setEnabled(false);
                jTextFieldDescrição.setEnabled(false);
                jTextFieldUnidade.setEnabled(false);
                jTextFieldFabricante.setEnabled(false);
                jComboBoxCategoria.setEnabled(false);
                jTextFieldPrecoCusto.setEnabled(false);
                jTextFieldPrecoVenda.setEnabled(false);
                jTextFieldQtdeAtual.setEnabled(false);
                jTextFieldQtdeMinima.setEnabled(false);               
                jTextFieldIDFornecedor.setEnabled(false);
                jComboBoxFornecedor.setEnabled(false);               
                jTextFieldPesquisaCliente.setEnabled(true);

                jButtonNovo.setEnabled(true);
                jButtonSalvar.setEnabled(false);
                jButtonEditar.setEnabled(false);
                jButtonCancelar.setEnabled(false);
                jButtonExcluir.setEnabled(false);
                jButtonPesquisar.setEnabled(true);
                preencherTabela("select *from produtos order by descricao_produto");

                // FUNÇÃO ALTERAR DADOS

            }else{

                mod.setIDProduto(Integer.parseInt(jTextFieldIDProduto.getText()));
                mod.setDataCadastro(jTextFieldDataCadastro.getText());
                mod.setDescricao(jTextFieldDescrição.getText());
                mod.setUnidade(jTextFieldUnidade.getText());        
                mod.setFabricante(jTextFieldFabricante.getText());
                mod.setCategoria((String)jComboBoxCategoria.getSelectedItem());
                mod.setPrecoCusto(Float.valueOf(jTextFieldPrecoCusto.getText()));
                mod.setPrecoVenda(Float.valueOf(jTextFieldPrecoVenda.getText()));
                mod.setQtdeAtual(Integer.parseInt(jTextFieldQtdeAtual.getText()));
                mod.setQtdeMinima(Integer.parseInt(jTextFieldQtdeMinima.getText()));                
                mod.setIDFornecedor(Integer.parseInt(jTextFieldIDFornecedor.getText()));
                mod.setFornecedor((String)jComboBoxFornecedor.getSelectedItem());                
                dao.Alterar(mod);

                    /*jTextFieldID.setText("");
                    jTextFieldDataCadastro.setText("");
                    jTextFieldNome.setText("");
                    jTextFieldEndereco.setText("");
                    jTextFieldNumero.setText("");
                    jTextFieldCidade.setText("");
                    jTextFieldEstado.setText("");
                    jTextFieldCEP.setText("");
                    jTextFieldBairro.setText("");
                    jTextFieldTelefone.setText("");
                    jTextFieldCelular.setText("");
                    jTextFieldEmail.setText("");
                    jTextPaneObservacoes.setText("");
                    jTextFieldPesquisaCliente.setText("");
                    */

                    jTextFieldIDProduto.setEnabled(false);
                    jTextFieldDataCadastro.setEnabled(false);
                    jTextFieldDescrição.setEnabled(false);
                    jTextFieldUnidade.setEnabled(false);
                    jTextFieldFabricante.setEnabled(false);
                    jComboBoxCategoria.setEnabled(false);
                    jTextFieldPrecoCusto.setEnabled(false);
                    jTextFieldPrecoVenda.setEnabled(false);
                    jTextFieldQtdeAtual.setEnabled(false);
                    jTextFieldQtdeMinima.setEnabled(false);                   
                    jTextFieldIDFornecedor.setEnabled(false);
                    jComboBoxFornecedor.setEnabled(false);                    
                    jTextFieldPesquisaCliente.setEnabled(true);
                    
                    jTableProdutos.setVisible(true);

                    jButtonNovo.setEnabled(true);
                    jButtonSalvar.setEnabled(false);
                    jButtonEditar.setEnabled(false);
                    jButtonCancelar.setEnabled(false);
                    jButtonExcluir.setEnabled(false);
                    jButtonPesquisar.setEnabled(true);
                    preencherTabela("select *from produtos order by descricao_produto");

                }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;
        
        jTextFieldDataCadastro.setEnabled(true);
        jTextFieldDescrição.setEnabled(true);
        jTextFieldUnidade.setEnabled(true);
        jTextFieldFabricante.setEnabled(true);
        jComboBoxCategoria.setEnabled(true);
        jTextFieldPrecoCusto.setEnabled(true);
        jTextFieldPrecoVenda.setEnabled(true);
        jTextFieldQtdeAtual.setEnabled(true);
        jTextFieldQtdeMinima.setEnabled(true);       
        jTextFieldIDFornecedor.setEnabled(true);
        jComboBoxFornecedor.setEnabled(true);
        
        jTextFieldPesquisaCliente.setEnabled(false);
        //jTableClientes.setEnabled(false);

        jTextFieldPesquisaCliente.setText("");

        jButtonNovo.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jButtonPesquisar.setEnabled(false);

    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldIDProduto.setEnabled(false);
        jTextFieldDataCadastro.setEnabled(false);
        jTextFieldDescrição.setEnabled(false);
        jTextFieldUnidade.setEnabled(false);
        jTextFieldFabricante.setEnabled(false);
        jComboBoxCategoria.setEnabled(false);
        jTextFieldPrecoCusto.setEnabled(false);
        jTextFieldPrecoVenda.setEnabled(false);
        jTextFieldQtdeAtual.setEnabled(false);
        jTextFieldQtdeMinima.setEnabled(false);       
        jTextFieldIDFornecedor.setEnabled(false);
        jComboBoxFornecedor.setEnabled(false);        
        jTextFieldPesquisaCliente.setEnabled(true);
        
        jTableProdutos.setVisible(true);

        /*jTextFieldID.setText("");
        jTextFieldDataCadastro.setText("");
        jTextFieldNome.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldNumero.setText("");
        jTextFieldCidade.setText("");
        jTextFieldEstado.setText("");
        jTextFieldCEP.setText("");
        jTextFieldBairro.setText("");
        jTextFieldTelefone.setText("");
        jTextFieldCelular.setText("");
        jTextFieldEmail.setText("");
        jTextPaneObservacoes.setText("");
        */

        jButtonNovo.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonPesquisar.setEnabled(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir o produto?");
        if(resposta == JOptionPane.YES_OPTION) {
            mod.setIDProduto(Integer.parseInt(jTextFieldIDProduto.getText()));
            dao.Excluir(mod);
            jTextFieldIDProduto.setText("");
            jTextFieldDataCadastro.setText("");
            jTextFieldDescrição.setText("");
            jTextFieldUnidade.setText("");
            jTextFieldFabricante.setText("");            
            jTextFieldPrecoCusto.setText("");
            jTextFieldPrecoVenda.setText("");
            jTextFieldQtdeAtual.setText("");
            jTextFieldQtdeMinima.setText("");           
            jTextFieldIDFornecedor.setText("");          
            jTextFieldPesquisaCliente.setText("");

            jTableProdutos.setVisible(true);

            jButtonNovo.setEnabled(true);
            jButtonSalvar.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            jButtonPesquisar.setEnabled(true);
            preencherTabela("select *from produtos order by descricao_produto");

        }

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroProdutos dialog = new CadastroProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxFornecedor;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelDataCadastro;
    private javax.swing.JLabel jLabelDescrição;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelFabricante;
    private javax.swing.JLabel jLabelFornecedor;
    private javax.swing.JLabel jLabelIDFornecedor;
    private javax.swing.JLabel jLabelIDProduto;
    private javax.swing.JLabel jLabelPesquisarCliente;
    private javax.swing.JLabel jLabelPrecoCusto;
    private javax.swing.JLabel jLabelPrecoVenda;
    private javax.swing.JLabel jLabelUnidade;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTextField jTextFieldDataCadastro;
    private javax.swing.JTextField jTextFieldDescrição;
    private javax.swing.JTextField jTextFieldFabricante;
    private javax.swing.JTextField jTextFieldIDFornecedor;
    private javax.swing.JTextField jTextFieldIDProduto;
    private javax.swing.JTextField jTextFieldPesquisaCliente;
    private javax.swing.JTextField jTextFieldPrecoCusto;
    private javax.swing.JTextField jTextFieldPrecoVenda;
    private javax.swing.JTextField jTextFieldQtdeAtual;
    private javax.swing.JTextField jTextFieldQtdeMinima;
    private javax.swing.JTextField jTextFieldUnidade;
    // End of variables declaration//GEN-END:variables
}
