/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Conexao.ConexaoBD;
import ModeloBeans.BeansCadFuncionarios;
import ModeloDao.DaoCadFuncionarios;
import ModeloDao.PreencherTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Jhonny_Queillia
 */
public class ModeloCadastro2 extends javax.swing.JDialog {
    ConexaoBD conecta = new ConexaoBD();
    BeansCadFuncionarios mod = new BeansCadFuncionarios();
    DaoCadFuncionarios dao =  new DaoCadFuncionarios();
    int flag = 0;

    /**
     * Creates new form CadastroProdutos
     */
    public ModeloCadastro2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        preencherTabela("select *from funcionarios order by nome_funcionario");
        
        
    }

    ModeloCadastro2() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPaneDadosCadastrais = new javax.swing.JTabbedPane();
        jPanelDadosCadastrais = new javax.swing.JPanel();
        jPanelDadosPessoais = new javax.swing.JPanel();
        jTextFieldIDFuncionario = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jComboBoxEstadoCivil = new javax.swing.JComboBox<>();
        jLabelIDFuncionario = new javax.swing.JLabel();
        jLabelDataCadastro = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelDataNasc = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jLabelEstadoCivil = new javax.swing.JLabel();
        jLabelRG = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        jLabelCTPS = new javax.swing.JLabel();
        jLabelSerie = new javax.swing.JLabel();
        jLabelPIS = new javax.swing.JLabel();
        jLabelTituloEleitor = new javax.swing.JLabel();
        jLabelZona = new javax.swing.JLabel();
        jLabelSecao = new javax.swing.JLabel();
        jFormattedTextFieldDataCadastro = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDataNasc = new javax.swing.JFormattedTextField();
        jFormattedTextFieldRG = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCTPS = new javax.swing.JFormattedTextField();
        jFormattedTextFieldSerie = new javax.swing.JFormattedTextField();
        jFormattedTextFieldPIS = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTitulo = new javax.swing.JFormattedTextField();
        jFormattedTextFieldZona = new javax.swing.JFormattedTextField();
        jFormattedTextFieldSecao = new javax.swing.JFormattedTextField();
        jPanelEndereco = new javax.swing.JPanel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldEstado = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabelEndereco = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelCEP = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        jLabelCelular = new javax.swing.JLabel();
        jFormattedTextFieldCEP = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCelular = new javax.swing.JFormattedTextField();
        jPanelCargo = new javax.swing.JPanel();
        jComboBoxCargo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneObservacoes = new javax.swing.JTextPane();
        jLabelCargo = new javax.swing.JLabel();
        jLabelObservacoes = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jPanelPesquisar = new javax.swing.JPanel();
        jPanelPesquisarFuncionarios = new javax.swing.JPanel();
        jTextFieldPesquisaFuncionario = new javax.swing.JTextField();
        jLabelPesquisarFuncionario = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFuncionarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO DE FUNCIONÁRIOS");

        jTabbedPaneDadosCadastrais.setForeground(new java.awt.Color(102, 102, 255));
        jTabbedPaneDadosCadastrais.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanelDadosPessoais.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldIDFuncionario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldIDFuncionario.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldIDFuncionario.setEnabled(false);

        jTextFieldNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldNome.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldNome.setEnabled(false);

        jComboBoxSexo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxSexo.setForeground(new java.awt.Color(102, 102, 255));
        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        jComboBoxSexo.setEnabled(false);

        jComboBoxEstadoCivil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxEstadoCivil.setForeground(new java.awt.Color(102, 102, 255));
        jComboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casado", "Separado", "Divorciado", "Viuvo", "Outro" }));
        jComboBoxEstadoCivil.setEnabled(false);

        jLabelIDFuncionario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelIDFuncionario.setForeground(new java.awt.Color(102, 102, 255));
        jLabelIDFuncionario.setText("ID");

        jLabelDataCadastro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDataCadastro.setForeground(new java.awt.Color(102, 102, 255));
        jLabelDataCadastro.setText("Data de Cadastro");

        jLabelNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(102, 102, 255));
        jLabelNome.setText("Nome");

        jLabelDataNasc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDataNasc.setForeground(new java.awt.Color(102, 102, 255));
        jLabelDataNasc.setText("Data Nasc.");

        jLabelSexo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSexo.setForeground(new java.awt.Color(102, 102, 255));
        jLabelSexo.setText("Sexo");

        jLabelEstadoCivil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelEstadoCivil.setForeground(new java.awt.Color(102, 102, 255));
        jLabelEstadoCivil.setText("Estado civil");

        jLabelRG.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelRG.setForeground(new java.awt.Color(102, 102, 255));
        jLabelRG.setText("RG");

        jLabelCPF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCPF.setForeground(new java.awt.Color(102, 102, 255));
        jLabelCPF.setText("CPF");

        jLabelCTPS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCTPS.setForeground(new java.awt.Color(102, 102, 255));
        jLabelCTPS.setText("CTPS");

        jLabelSerie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSerie.setForeground(new java.awt.Color(102, 102, 255));
        jLabelSerie.setText("Série");

        jLabelPIS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPIS.setForeground(new java.awt.Color(102, 102, 255));
        jLabelPIS.setText("PIS");

        jLabelTituloEleitor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTituloEleitor.setForeground(new java.awt.Color(102, 102, 255));
        jLabelTituloEleitor.setText("Título");

        jLabelZona.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelZona.setForeground(new java.awt.Color(102, 102, 255));
        jLabelZona.setText("Zona");

        jLabelSecao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSecao.setForeground(new java.awt.Color(102, 102, 255));
        jLabelSecao.setText("Seção");

        jFormattedTextFieldDataCadastro.setForeground(new java.awt.Color(102, 102, 255));
        try {
            jFormattedTextFieldDataCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataCadastro.setEnabled(false);
        jFormattedTextFieldDataCadastro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jFormattedTextFieldDataNasc.setForeground(new java.awt.Color(102, 102, 255));
        try {
            jFormattedTextFieldDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataNasc.setEnabled(false);
        jFormattedTextFieldDataNasc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jFormattedTextFieldRG.setForeground(new java.awt.Color(102, 102, 255));
        try {
            jFormattedTextFieldRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldRG.setEnabled(false);
        jFormattedTextFieldRG.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jFormattedTextFieldCPF.setForeground(new java.awt.Color(102, 102, 255));
        try {
            jFormattedTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF.setEnabled(false);
        jFormattedTextFieldCPF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jFormattedTextFieldCTPS.setForeground(new java.awt.Color(102, 102, 255));
        jFormattedTextFieldCTPS.setEnabled(false);
        jFormattedTextFieldCTPS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jFormattedTextFieldSerie.setForeground(new java.awt.Color(102, 102, 255));
        jFormattedTextFieldSerie.setEnabled(false);
        jFormattedTextFieldSerie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jFormattedTextFieldPIS.setForeground(new java.awt.Color(102, 102, 255));
        try {
            jFormattedTextFieldPIS.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.#####.##-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldPIS.setEnabled(false);
        jFormattedTextFieldPIS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jFormattedTextFieldTitulo.setForeground(new java.awt.Color(102, 102, 255));
        try {
            jFormattedTextFieldTitulo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####.####.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTitulo.setEnabled(false);
        jFormattedTextFieldTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jFormattedTextFieldZona.setForeground(new java.awt.Color(102, 102, 255));
        jFormattedTextFieldZona.setEnabled(false);
        jFormattedTextFieldZona.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jFormattedTextFieldSecao.setForeground(new java.awt.Color(102, 102, 255));
        jFormattedTextFieldSecao.setEnabled(false);
        jFormattedTextFieldSecao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanelDadosPessoaisLayout = new javax.swing.GroupLayout(jPanelDadosPessoais);
        jPanelDadosPessoais.setLayout(jPanelDadosPessoaisLayout);
        jPanelDadosPessoaisLayout.setHorizontalGroup(
            jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabelRG)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNome)
                                    .addComponent(jLabelIDFuncionario)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosPessoaisLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabelDataNasc)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextFieldDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabelSexo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(jTextFieldIDFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelDataCadastro)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFormattedTextFieldDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(41, 41, 41)
                                .addComponent(jLabelEstadoCivil)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelSerie)
                                    .addComponent(jLabelCPF)
                                    .addComponent(jLabelZona))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldZona, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldPIS, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldSecao, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTituloEleitor)
                            .addComponent(jLabelCTPS))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldCTPS, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabelPIS))
                            .addComponent(jLabelSecao, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelDadosPessoaisLayout.setVerticalGroup(
            jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIDFuncionario)
                    .addComponent(jTextFieldIDFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataCadastro)
                    .addComponent(jFormattedTextFieldDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataNasc)
                    .addComponent(jLabelSexo)
                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstadoCivil)
                    .addComponent(jFormattedTextFieldDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRG)
                    .addComponent(jLabelCPF)
                    .addComponent(jFormattedTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCTPS)
                    .addComponent(jLabelSerie)
                    .addComponent(jLabelPIS)
                    .addComponent(jFormattedTextFieldCTPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldPIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTituloEleitor)
                    .addComponent(jLabelZona)
                    .addComponent(jLabelSecao)
                    .addComponent(jFormattedTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldSecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelEndereco.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldEndereco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldEndereco.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldEndereco.setEnabled(false);

        jTextFieldNumero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldNumero.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldNumero.setEnabled(false);

        jTextFieldCidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCidade.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldCidade.setEnabled(false);

        jTextFieldEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldEstado.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldEstado.setEnabled(false);

        jTextFieldBairro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldBairro.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldBairro.setEnabled(false);

        jLabelEndereco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelEndereco.setForeground(new java.awt.Color(102, 102, 255));
        jLabelEndereco.setText("Endereço");

        jLabelNumero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNumero.setForeground(new java.awt.Color(102, 102, 255));
        jLabelNumero.setText("Nº");

        jLabelCidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCidade.setForeground(new java.awt.Color(102, 102, 255));
        jLabelCidade.setText("Cidade");

        jLabelEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelEstado.setForeground(new java.awt.Color(102, 102, 255));
        jLabelEstado.setText("Estado");

        jLabelCEP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCEP.setForeground(new java.awt.Color(102, 102, 255));
        jLabelCEP.setText("CEP");

        jLabelBairro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelBairro.setForeground(new java.awt.Color(102, 102, 255));
        jLabelBairro.setText("Bairro");

        jLabelTelefone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTelefone.setForeground(new java.awt.Color(102, 102, 255));
        jLabelTelefone.setText("Telefone");

        jLabelCelular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCelular.setForeground(new java.awt.Color(102, 102, 255));
        jLabelCelular.setText("Celular");

        jFormattedTextFieldCEP.setForeground(new java.awt.Color(102, 102, 255));
        try {
            jFormattedTextFieldCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCEP.setEnabled(false);

        jFormattedTextFieldTelefone.setForeground(new java.awt.Color(102, 102, 255));
        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone.setEnabled(false);
        jFormattedTextFieldTelefone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jFormattedTextFieldCelular.setForeground(new java.awt.Color(102, 102, 255));
        try {
            jFormattedTextFieldCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCelular.setEnabled(false);
        jFormattedTextFieldCelular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanelEnderecoLayout = new javax.swing.GroupLayout(jPanelEndereco);
        jPanelEndereco.setLayout(jPanelEnderecoLayout);
        jPanelEnderecoLayout.setHorizontalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCidade)
                    .addComponent(jLabelEndereco)
                    .addComponent(jLabelBairro)
                    .addComponent(jLabelTelefone))
                .addGap(18, 18, 18)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                            .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCelular)
                            .addGap(18, 18, 18)
                            .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                                .addComponent(jLabelEstado)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNumero)
                    .addComponent(jLabelCEP))
                .addGap(18, 18, 18)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEnderecoLayout.setVerticalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEndereco)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumero)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidade)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstado)
                    .addComponent(jLabelCEP)
                    .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBairro))
                .addGap(18, 18, 18)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefone)
                    .addComponent(jLabelCelular)
                    .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanelCargo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBoxCargo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxCargo.setForeground(new java.awt.Color(102, 102, 255));
        jComboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Gerente" }));
        jComboBoxCargo.setEnabled(false);

        jTextPaneObservacoes.setEnabled(false);
        jScrollPane1.setViewportView(jTextPaneObservacoes);

        jLabelCargo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCargo.setForeground(new java.awt.Color(102, 102, 255));
        jLabelCargo.setText("Cargo");

        jLabelObservacoes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelObservacoes.setForeground(new java.awt.Color(102, 102, 255));
        jLabelObservacoes.setText("Observações");

        javax.swing.GroupLayout jPanelCargoLayout = new javax.swing.GroupLayout(jPanelCargo);
        jPanelCargo.setLayout(jPanelCargoLayout);
        jPanelCargoLayout.setHorizontalGroup(
            jPanelCargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCargoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelObservacoes)
                    .addComponent(jLabelCargo))
                .addGap(18, 18, 18)
                .addGroup(jPanelCargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCargoLayout.setVerticalGroup(
            jPanelCargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCargoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCargo)
                    .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelObservacoes))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(102, 102, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNovo.setForeground(new java.awt.Color(102, 102, 255));
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(102, 102, 255));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(102, 102, 255));
        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluir.setForeground(new java.awt.Color(102, 102, 255));
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDadosCadastraisLayout = new javax.swing.GroupLayout(jPanelDadosCadastrais);
        jPanelDadosCadastrais.setLayout(jPanelDadosCadastraisLayout);
        jPanelDadosCadastraisLayout.setHorizontalGroup(
            jPanelDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosCadastraisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosCadastraisLayout.createSequentialGroup()
                        .addGroup(jPanelDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanelCargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelDadosPessoais, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelEndereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosCadastraisLayout.createSequentialGroup()
                        .addComponent(jButtonNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSalvar)
                        .addGap(11, 11, 11)
                        .addComponent(jButtonEditar)
                        .addGap(11, 11, 11)
                        .addComponent(jButtonCancelar)
                        .addGap(7, 7, 7)
                        .addComponent(jButtonExcluir)
                        .addContainerGap())))
        );
        jPanelDadosCadastraisLayout.setVerticalGroup(
            jPanelDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosCadastraisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosCadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSalvar)
                        .addComponent(jButtonNovo))
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneDadosCadastrais.addTab("DADOS CADASTRAIS", jPanelDadosCadastrais);

        jPanelPesquisarFuncionarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldPesquisaFuncionario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldPesquisaFuncionario.setForeground(new java.awt.Color(102, 102, 255));

        jLabelPesquisarFuncionario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPesquisarFuncionario.setForeground(new java.awt.Color(102, 102, 255));
        jLabelPesquisarFuncionario.setText("Pesquisar Funcionário");

        jButtonPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPesquisar.setForeground(new java.awt.Color(102, 102, 255));
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jTableFuncionarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableFuncionarios.setForeground(new java.awt.Color(102, 102, 255));
        jTableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableFuncionarios);

        javax.swing.GroupLayout jPanelPesquisarFuncionariosLayout = new javax.swing.GroupLayout(jPanelPesquisarFuncionarios);
        jPanelPesquisarFuncionarios.setLayout(jPanelPesquisarFuncionariosLayout);
        jPanelPesquisarFuncionariosLayout.setHorizontalGroup(
            jPanelPesquisarFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisarFuncionariosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelPesquisarFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPesquisarFuncionariosLayout.createSequentialGroup()
                        .addComponent(jLabelPesquisarFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisar)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanelPesquisarFuncionariosLayout.setVerticalGroup(
            jPanelPesquisarFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisarFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPesquisarFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jLabelPesquisarFuncionario)
                    .addComponent(jTextFieldPesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPesquisarLayout = new javax.swing.GroupLayout(jPanelPesquisar);
        jPanelPesquisar.setLayout(jPanelPesquisarLayout);
        jPanelPesquisarLayout.setHorizontalGroup(
            jPanelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPesquisarFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPesquisarLayout.setVerticalGroup(
            jPanelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPesquisarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPaneDadosCadastrais.addTab("PESQUISAR", jPanelPesquisar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPaneDadosCadastrais))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneDadosCadastrais)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        mod.setPesquisar(jTextFieldPesquisaFuncionario.getText());
        BeansCadFuncionarios model = dao.BuscaFuncionario(mod);
        jTextFieldIDFuncionario.setText(String.valueOf(model.getID()));
        jFormattedTextFieldDataCadastro.setText(model.getDataCadastro());
        jTextFieldNome.setText(model.getNome());
        jFormattedTextFieldDataNasc.setText(model.getDataNasc());
        jComboBoxSexo.setSelectedItem(model.getSexo());
        jComboBoxEstadoCivil.setSelectedItem(model.getEstadoCivil());
        jFormattedTextFieldRG.setText(model.getRG());
        jFormattedTextFieldCPF.setText(model.getCPF());
        jFormattedTextFieldCTPS.setText(String.valueOf(model.getCTPS()));
        jFormattedTextFieldSerie.setText(model.getSerie());
        jFormattedTextFieldPIS.setText(model.getPIS());
        jFormattedTextFieldTitulo.setText(model.getTitulo());
        jFormattedTextFieldZona.setText(String.valueOf(model.getZona()));
        jFormattedTextFieldSecao.setText(String.valueOf(model.getSecao()));
        jTextFieldEndereco.setText(model.getEndereco());
        jTextFieldNumero.setText(String.valueOf(model.getNumero()));
        jTextFieldCidade.setText(model.getCidade());
        jTextFieldEstado.setText(model.getEstado());
        jFormattedTextFieldCEP.setText(model.getCEP());
        jTextFieldBairro.setText(model.getBairro());
        jFormattedTextFieldTelefone.setText(model.getTelefone());
        jFormattedTextFieldCelular.setText(model.getCelular());
        jComboBoxCargo.setSelectedItem(model.getCargo());
        jTextPaneObservacoes.setText(model.getObs());

        jTextFieldPesquisaFuncionario.setText("");

        jButtonNovo.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        //jButtonPesquisar.setEnabled(false);
        preencherTabela("select *from funcionarios where nome_funcionario like'%"+mod.getPesquisar()+"%'");
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTableFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFuncionariosMouseClicked
        String nome_funcionario = "" + jTableFuncionarios.getValueAt(jTableFuncionarios.getSelectedRow(), 2);
        conecta.conexao();
        conecta.executaSQL("select *from funcionarios where nome_funcionario = '"+ nome_funcionario + "'");
        try {
            conecta.rs.first();
            jTextFieldIDFuncionario.setText(String.valueOf(conecta.rs.getInt("id_funcionario")));
            jFormattedTextFieldDataCadastro.setText(conecta.rs.getString("datacadastro_funcionario"));
            jTextFieldNome.setText(conecta.rs.getString("nome_funcionario"));
            jFormattedTextFieldDataNasc.setText(conecta.rs.getString("datanasc_funcionario"));
            jComboBoxSexo.setSelectedItem(conecta.rs.getString("sexo_funcionario"));
            jComboBoxEstadoCivil.setSelectedItem(conecta.rs.getString("estadocivil_funcionario"));
            jFormattedTextFieldRG.setText(conecta.rs.getString("rg_funcionario"));
            jFormattedTextFieldCPF.setText(conecta.rs.getString("cpf_funcionario"));
            jFormattedTextFieldCTPS.setText(String.valueOf(conecta.rs.getInt("ctps_funcionario")));
            jFormattedTextFieldSerie.setText(conecta.rs.getString("serie_funcionario"));
            jFormattedTextFieldPIS.setText(conecta.rs.getString("pis_funcionario"));
            jFormattedTextFieldTitulo.setText(conecta.rs.getString("titulo_funcionario"));
            jFormattedTextFieldZona.setText(String.valueOf(conecta.rs.getInt("zonaeleitoral_funcionario")));
            jFormattedTextFieldSecao.setText(String.valueOf(conecta.rs.getInt("secaoeleitoral_funcionario")));
            jTextFieldEndereco.setText(conecta.rs.getString("endereco_funcionario"));
            jTextFieldNumero.setText(String.valueOf(conecta.rs.getInt("numero_funcionario")));
            jTextFieldCidade.setText(conecta.rs.getString("cidade_funcionario"));
            jTextFieldEstado.setText(conecta.rs.getString("estado_funcionario"));
            jFormattedTextFieldCEP.setText(conecta.rs.getString("cep_funcionario"));
            jTextFieldBairro.setText(conecta.rs.getString("bairro_funcionario"));
            jFormattedTextFieldTelefone.setText(conecta.rs.getString("telefone_funcionario"));
            jFormattedTextFieldCelular.setText(conecta.rs.getString("celular_funcionario"));
            jComboBoxCargo.setSelectedItem(conecta.rs.getString("cargo_funcionario"));
            jTextPaneObservacoes.setText(conecta.rs.getString("obs_funcionario"));

        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar item!"+ex);
        }
        jButtonNovo.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonPesquisar.setEnabled(false);
        //jTableClientes.setEnabled(false);
        jTableFuncionarios.setVisible(false);
        jTabbedPaneDadosCadastrais.setSelectedComponent(jPanelDadosCadastrais);

        jTextFieldPesquisaFuncionario.setText("");

        conecta.desconexao();

    }//GEN-LAST:event_jTableFuncionariosMouseClicked

    public void preencherTabela(String Sql) {
        ArrayList dados = new ArrayList();
        String [] colunas = new String [] {"ID","Data de Cadastro","Nome Funcionário","Data de Nasc","Sexo","Estado Civil","RG","CPF","CTPS","Série","PIS","Titulo de eleitor","Zona eleitoral","Seção eleitoral","Endereço","Número","Cidade","Estado","CEP","Bairro","Telefone","Celular","Cargo","Observações"};
        conecta.conexao();
        conecta.executaSQL(Sql);
        
        try{
            conecta.rs.first();
            do{
                dados.add(new Object[] {conecta.rs.getInt("id_funcionario"),conecta.rs.getString("datacadastro_funcionario"),conecta.rs.getString("nome_funcionario"),conecta.rs.getString("datanasc_funcionario"),conecta.rs.getString("sexo_funcionario"),conecta.rs.getString("estadocivil_funcionario"),conecta.rs.getString("rg_funcionario"),conecta.rs.getString("cpf_funcionario"),conecta.rs.getInt("ctps_funcionario"),conecta.rs.getString("pis_funcionario"),conecta.rs.getInt("zonaeleitoral_funcionario"),conecta.rs.getInt("secaoeleitoral_funcionario"),conecta.rs.getString("endereco_funcionario"),conecta.rs.getInt("numero_funcionario"),conecta.rs.getString("cidade_funcionario"),conecta.rs.getString("estado_funcionario"),conecta.rs.getString("cep_funcionario"),conecta.rs.getString("bairro_funcionario"),conecta.rs.getString("telefone_funcionario"),conecta.rs.getString("celular_funcionario"),conecta.rs.getString("cargo_funcionario"),conecta.rs.getString("obs_funcionario"),conecta.rs.getString("serie_funcionario"),conecta.rs.getString("titulo _funcionario")});                
            }while(conecta.rs.next());                    
        }catch(SQLException ex) {
            
// Preenchendo a tabela
            //JOptionPane.showMessageDialog(rootPane, "Faça uma nova busca, pois os dados pesquisados não existem!");
        }
        PreencherTabela modelo = new PreencherTabela(dados, colunas);
        
        jTableFuncionarios.setModel(modelo);        
        jTableFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableFuncionarios.getColumnModel().getColumn(0).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(1).setPreferredWidth(120);
        jTableFuncionarios.getColumnModel().getColumn(1).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(2).setPreferredWidth(240);
        jTableFuncionarios.getColumnModel().getColumn(2).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(3).setPreferredWidth(60);
        jTableFuncionarios.getColumnModel().getColumn(3).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(4).setPreferredWidth(160);
        jTableFuncionarios.getColumnModel().getColumn(4).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(5).setPreferredWidth(160);
        jTableFuncionarios.getColumnModel().getColumn(5).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(6).setPreferredWidth(100);
        jTableFuncionarios.getColumnModel().getColumn(6).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(7).setPreferredWidth(100);
        jTableFuncionarios.getColumnModel().getColumn(7).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(8).setPreferredWidth(80);
        jTableFuncionarios.getColumnModel().getColumn(8).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(9).setPreferredWidth(80);
        jTableFuncionarios.getColumnModel().getColumn(9).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(10).setPreferredWidth(40);
        jTableFuncionarios.getColumnModel().getColumn(10).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(11).setPreferredWidth(280);
        jTableFuncionarios.getColumnModel().getColumn(11).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableFuncionarios.getColumnModel().getColumn(0).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(1).setPreferredWidth(120);
        jTableFuncionarios.getColumnModel().getColumn(1).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(2).setPreferredWidth(240);
        jTableFuncionarios.getColumnModel().getColumn(2).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(3).setPreferredWidth(60);
        jTableFuncionarios.getColumnModel().getColumn(3).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(4).setPreferredWidth(160);
        jTableFuncionarios.getColumnModel().getColumn(4).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(5).setPreferredWidth(160);
        jTableFuncionarios.getColumnModel().getColumn(5).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(6).setPreferredWidth(100);
        jTableFuncionarios.getColumnModel().getColumn(6).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(7).setPreferredWidth(100);
        jTableFuncionarios.getColumnModel().getColumn(7).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(8).setPreferredWidth(80);
        jTableFuncionarios.getColumnModel().getColumn(8).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(9).setPreferredWidth(80);
        jTableFuncionarios.getColumnModel().getColumn(9).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(10).setPreferredWidth(40);
        jTableFuncionarios.getColumnModel().getColumn(10).setResizable(false);
        
        jTableFuncionarios.getColumnModel().getColumn(11).setPreferredWidth(280);
        jTableFuncionarios.getColumnModel().getColumn(11).setResizable(false);
        
        jTableFuncionarios.getTableHeader().setReorderingAllowed(false);
        jTableFuncionarios.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTableFuncionarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);      
        
        conecta.desconexao();
        
    }                        
    
    
    
    
    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir o funcionário?");
        if(resposta == JOptionPane.YES_OPTION) {
            mod.setID(Integer.parseInt(jTextFieldIDFuncionario.getText()));
            dao.Excluir(mod);

            jTextFieldIDFuncionario.setText("");
            jFormattedTextFieldDataCadastro.setText("");
            jTextFieldNome.setText("");
            jFormattedTextFieldDataNasc.setText("");
            jComboBoxSexo.setSelectedItem(null);
            jComboBoxEstadoCivil.setSelectedItem(null);
            jFormattedTextFieldRG.setText("");
            jFormattedTextFieldCPF.setText("");
            jFormattedTextFieldCTPS.setText("");
            jFormattedTextFieldSerie.setText("");
            jFormattedTextFieldPIS.setText("");
            jFormattedTextFieldTitulo.setText("");
            jFormattedTextFieldZona.setText("");
            jFormattedTextFieldSecao.setText("");
            jTextFieldEndereco.setText("");
            jTextFieldNumero.setText("");
            jTextFieldCidade.setText("");
            jTextFieldEstado.setText("");
            jFormattedTextFieldCEP.setText("");
            jTextFieldBairro.setText("");
            jFormattedTextFieldTelefone.setText("");
            jFormattedTextFieldCelular.setText("");            
            jComboBoxCargo.setSelectedItem(null);
            jTextPaneObservacoes.setText("");
            
            jTextFieldIDFuncionario.setEnabled(false);
            jFormattedTextFieldDataCadastro.setEnabled(false);
            jTextFieldNome.setEnabled(false);
            jFormattedTextFieldDataNasc.setEnabled(false);
            jComboBoxSexo.setEnabled(false);
            jComboBoxEstadoCivil.setEnabled(false);
            jFormattedTextFieldRG.setEnabled(false);
            jFormattedTextFieldCPF.setEnabled(false);
            jFormattedTextFieldCTPS.setEnabled(false);
            jFormattedTextFieldSerie.setEnabled(false);
            jFormattedTextFieldPIS.setEnabled(false);
            jFormattedTextFieldTitulo.setEnabled(false);
            jFormattedTextFieldZona.setEnabled(false);
            jFormattedTextFieldSecao.setEnabled(false);
            jTextFieldEndereco.setEnabled(false);
            jTextFieldNumero.setEnabled(false);
            jTextFieldCidade.setEnabled(false);
            jTextFieldEstado.setEnabled(false);
            jFormattedTextFieldCEP.setEnabled(false);
            jTextFieldBairro.setEnabled(false);
            jFormattedTextFieldTelefone.setEnabled(false);
            jFormattedTextFieldCelular.setEnabled(false);
            jComboBoxCargo.setEnabled(false);            
            jTextPaneObservacoes.setEnabled(false);

            jTextFieldPesquisaFuncionario.setText("");
           
            jTableFuncionarios.setVisible(true);

            jButtonNovo.setEnabled(true);
            jButtonSalvar.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            jButtonPesquisar.setEnabled(true);
            preencherTabela("select *from produtos order by descricao_produto");

        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
            jTextFieldIDFuncionario.setText("");
            jFormattedTextFieldDataCadastro.setText("");
            jTextFieldNome.setText("");
            jFormattedTextFieldDataNasc.setText("");
            jComboBoxSexo.setSelectedItem(null);
            jComboBoxEstadoCivil.setSelectedItem(null);
            jFormattedTextFieldRG.setText("");
            jFormattedTextFieldCPF.setText("");
            jFormattedTextFieldCTPS.setText("");
            jFormattedTextFieldSerie.setText("");
            jFormattedTextFieldPIS.setText("");
            jFormattedTextFieldTitulo.setText("");
            jFormattedTextFieldZona.setText("");
            jFormattedTextFieldSecao.setText("");
            jTextFieldEndereco.setText("");
            jTextFieldNumero.setText("");
            jTextFieldCidade.setText("");
            jTextFieldEstado.setText("");
            jFormattedTextFieldCEP.setText("");
            jTextFieldBairro.setText("");
            jFormattedTextFieldTelefone.setText("");
            jFormattedTextFieldCelular.setText("");            
            jComboBoxCargo.setSelectedItem(null);
            jTextPaneObservacoes.setText("");       
        
        jTextFieldIDFuncionario.setEnabled(false);
        jFormattedTextFieldDataCadastro.setEnabled(false);
        jTextFieldNome.setEnabled(false);
        jFormattedTextFieldDataNasc.setEnabled(false);
        jComboBoxSexo.setEnabled(false);
        jComboBoxEstadoCivil.setEnabled(false);
        jFormattedTextFieldRG.setEnabled(false);
        jFormattedTextFieldCPF.setEnabled(false);
        jFormattedTextFieldCTPS.setEnabled(false);
        jFormattedTextFieldSerie.setEnabled(false);
        jFormattedTextFieldPIS.setEnabled(false);
        jFormattedTextFieldTitulo.setEnabled(false);
        jFormattedTextFieldZona.setEnabled(false);
        jFormattedTextFieldSecao.setEnabled(false);
        jTextFieldEndereco.setEnabled(false);
        jTextFieldNumero.setEnabled(false);
        jTextFieldCidade.setEnabled(false);
        jTextFieldEstado.setEnabled(false);
        jFormattedTextFieldCEP.setEnabled(false);
        jTextFieldBairro.setEnabled(false);
        jFormattedTextFieldTelefone.setEnabled(false);
        jFormattedTextFieldCelular.setEnabled(false);
        jComboBoxCargo.setEnabled(false);            
        jTextPaneObservacoes.setEnabled(false);

        jTextFieldPesquisaFuncionario.setEnabled(true);

        jTableFuncionarios.setVisible(true);

        jButtonNovo.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonPesquisar.setEnabled(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;

        jFormattedTextFieldDataCadastro.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jFormattedTextFieldDataNasc.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        jComboBoxEstadoCivil.setEnabled(true);
        jFormattedTextFieldRG.setEnabled(true);
        jFormattedTextFieldCPF.setEnabled(true);
        jFormattedTextFieldCTPS.setEnabled(true);
        jFormattedTextFieldSerie.setEnabled(true);
        jFormattedTextFieldPIS.setEnabled(true);
        jFormattedTextFieldTitulo.setEnabled(true);
        jFormattedTextFieldZona.setEnabled(true);
        jFormattedTextFieldSecao.setEnabled(true);
        jTextFieldEndereco.setEnabled(true);
        jTextFieldNumero.setEnabled(true);
        jTextFieldCidade.setEnabled(true);
        jTextFieldEstado.setEnabled(true);
        jFormattedTextFieldCEP.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);
        jFormattedTextFieldCelular.setEnabled(true);
        jComboBoxCargo.setEnabled(true);            
        jTextPaneObservacoes.setEnabled(true);

        jTextFieldPesquisaFuncionario.setEnabled(false);

        jTextFieldPesquisaFuncionario.setText("");

        jButtonNovo.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jButtonPesquisar.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
                
        jFormattedTextFieldDataCadastro.requestFocus();
        jFormattedTextFieldDataCadastro.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jFormattedTextFieldDataNasc.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        jComboBoxEstadoCivil.setEnabled(true);
        jFormattedTextFieldRG.setEnabled(true);
        jFormattedTextFieldCPF.setEnabled(true);
        jFormattedTextFieldCTPS.setEnabled(true);
        jFormattedTextFieldSerie.setEnabled(true);
        jFormattedTextFieldPIS.setEnabled(true);
        jFormattedTextFieldTitulo.setEnabled(true);
        jFormattedTextFieldZona.setEnabled(true);
        jFormattedTextFieldSecao.setEnabled(true);
        jTextFieldEndereco.setEnabled(true);
        jTextFieldNumero.setEnabled(true);
        jTextFieldCidade.setEnabled(true);
        jTextFieldEstado.setEnabled(true);
        jFormattedTextFieldCEP.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);
        jFormattedTextFieldCelular.setEnabled(true);
        jComboBoxCargo.setEnabled(true);
        jTextPaneObservacoes.setEnabled(true);
        jTextFieldPesquisaFuncionario.setEnabled(false);

        jTextFieldIDFuncionario.setText("");
        jFormattedTextFieldDataCadastro.setText("");
        jTextFieldNome.setText("");
        jFormattedTextFieldDataNasc.setText("");
        jComboBoxSexo.setSelectedItem(null);
        jComboBoxEstadoCivil.setSelectedItem(null);
        jFormattedTextFieldRG.setText("");
        jFormattedTextFieldCPF.setText("");
        jFormattedTextFieldCTPS.setText("");
        jFormattedTextFieldSerie.setText("");
        jFormattedTextFieldPIS.setText("");
        jFormattedTextFieldTitulo.setText("");
        jFormattedTextFieldZona.setText("");
        jFormattedTextFieldSecao.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldNumero.setText("");
        jTextFieldCidade.setText("");
        jTextFieldEstado.setText("");
        jFormattedTextFieldCEP.setText("");
        jTextFieldBairro.setText("");
        jFormattedTextFieldTelefone.setText("");
        jFormattedTextFieldCelular.setText("");
        jComboBoxCargo.setSelectedItem(null);
        jTextPaneObservacoes.setText("");
        jTextFieldPesquisaFuncionario.setText("");

        jButtonNovo.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jButtonPesquisar.setEnabled(false);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if(jFormattedTextFieldDataCadastro.getText().trim().length() < 10 || jFormattedTextFieldDataCadastro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo DATA DE CADASTRO para prosseguir");
            jFormattedTextFieldDataCadastro.requestFocus();
        }else if (jTextFieldNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo NOME para prosseguir");
            jTextFieldNome.requestFocus();
        }else if (jFormattedTextFieldDataNasc.getText().trim().length() < 10 || jFormattedTextFieldDataNasc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo DATA DE NASCIMENTO para prosseguir");
            jFormattedTextFieldDataNasc.requestFocus();
            
        /*}else if (jComboBoxSexo.getSelectedItem()== "") {
            JOptionPane.showMessageDialog(null, "Preencha o campo DATA DE NASCIMENTO para prosseguir");
            jComboBoxSexo.requestFocus();
            
            /*if ( ((String)comboBox.getSelectedItem()).equals("") ) {
                            JOptionPane.showMessageDialog(null, "Nada foi selecionado");*/
            
           //((String)(jComboBoxSexo.getSelectedItem()));            
        
        }else if (jFormattedTextFieldRG.getText().trim().length() < 12 || jFormattedTextFieldRG.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo RG para prosseguir");
            jFormattedTextFieldRG.requestFocus();
        }else if (jFormattedTextFieldCPF.getText().trim().length() < 14 || jFormattedTextFieldCPF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo CPF para prosseguir");
            jFormattedTextFieldCPF.requestFocus();
        }else if (jFormattedTextFieldCTPS.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo CTPS para prosseguir");
            jFormattedTextFieldCTPS.requestFocus();
        }else if (jFormattedTextFieldSerie.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo SÉRIE para prosseguir");
            jFormattedTextFieldSerie.requestFocus();
        }else if (jFormattedTextFieldPIS.getText().trim().length() < 14 || jFormattedTextFieldPIS.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo PIS para prosseguir");
            jFormattedTextFieldPIS.requestFocus();
        }else if (jFormattedTextFieldTitulo.getText().trim().length() < 14 || jFormattedTextFieldTitulo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo TÍTULO DE ELEITOR para prosseguir");
            jFormattedTextFieldTitulo.requestFocus();
        }else if (jFormattedTextFieldZona.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo ZONA para prosseguir");
            jFormattedTextFieldZona.requestFocus();
        }else if (jFormattedTextFieldSecao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo SEÇÃO para prosseguir");
            jFormattedTextFieldSecao.requestFocus();
        }else if (jTextFieldEndereco.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo ENDEREÇO para prosseguir");
            jLabelEndereco.requestFocus();
        }else if (jTextFieldNumero.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo NÚMERO para prosseguir");
            jTextFieldNumero.requestFocus();
        }else if (jTextFieldCidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo CIDADE para prosseguir");
            jTextFieldCidade.requestFocus();
        }else if (jTextFieldEstado.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo ESTADO para prosseguir");
            jTextFieldEstado.requestFocus();
        }else if (jFormattedTextFieldCEP.getText().trim().length() < 10 || jFormattedTextFieldCEP.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo CEP para prosseguir");
            jFormattedTextFieldCEP.requestFocus();
        }else if (jTextFieldBairro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo BAIRRO para prosseguir");
            jTextFieldBairro.requestFocus();
        }else if (jFormattedTextFieldTelefone.getText().trim().length() < 13 || jFormattedTextFieldTelefone.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo TELEFONE para prosseguir");
            jFormattedTextFieldTelefone.requestFocus();
        }else if (jFormattedTextFieldCelular.getText().trim().length() < 14 || jFormattedTextFieldCelular.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo CELULAR para prosseguir");
            jFormattedTextFieldCelular.requestFocus();

        }else

        // FUNÇÃO INSERIR DADOS

        if(flag==1) {

            mod.setDataCadastro(jFormattedTextFieldDataCadastro.getText());
            mod.setNome(jTextFieldNome.getText());
            mod.setDataNasc(jFormattedTextFieldDataNasc.getText());
            mod.setSexo((String)(jComboBoxSexo.getSelectedItem()));
            mod.setEstadoCivil((String)(jComboBoxEstadoCivil.getSelectedItem()));
            mod.setRG(jFormattedTextFieldRG.getText());
            mod.setCPF(jFormattedTextFieldCPF.getText());
            mod.setCTPS(Integer.parseInt(jFormattedTextFieldCTPS.getText()));
            mod.setSerie(jFormattedTextFieldSerie.getText());
            mod.setPIS(jFormattedTextFieldPIS.getText());
            mod.setTitulo(jFormattedTextFieldTitulo.getText());
            mod.setZona(Integer.parseInt(jFormattedTextFieldZona.getText()));
            mod.setSecao(Integer.parseInt(jFormattedTextFieldSecao.getText()));
            mod.setEndereco(jTextFieldEndereco.getText());
            mod.setNumero(Integer.parseInt(jTextFieldNumero.getText()));
            mod.setCidade(jTextFieldCidade.getText());
            mod.setEstado(jTextFieldEstado.getText());
            mod.setCEP(jFormattedTextFieldCEP.getText());
            mod.setBairro(jTextFieldBairro.getText());
            mod.setTelefone(jFormattedTextFieldTelefone.getText());
            mod.setCelular(jFormattedTextFieldCelular.getText());
            mod.setCargo((String)(jComboBoxCargo.getSelectedItem()));
            mod.setObs(jTextPaneObservacoes.getText());
            dao.Salvar(mod);

            jTextFieldIDFuncionario.setText("");
            jFormattedTextFieldDataCadastro.setText("");
            jTextFieldNome.setText("");
            jFormattedTextFieldDataNasc.setText("");
            jComboBoxSexo.setSelectedItem(null);
            jComboBoxEstadoCivil.setSelectedItem(null);
            jFormattedTextFieldRG.setText("");
            jFormattedTextFieldCPF.setText("");
            jFormattedTextFieldCTPS.setText("");
            jFormattedTextFieldSerie.setText("");
            jFormattedTextFieldPIS.setText("");
            jFormattedTextFieldTitulo.setText("");
            jFormattedTextFieldZona.setText("");
            jFormattedTextFieldSecao.setText("");
            jTextFieldEndereco.setText("");
            jTextFieldNumero.setText("");
            jTextFieldCidade.setText("");
            jTextFieldEstado.setText("");
            jFormattedTextFieldCEP.setText("");
            jTextFieldBairro.setText("");
            jFormattedTextFieldTelefone.setText("");
            jFormattedTextFieldCelular.setText("");
            jComboBoxCargo.setSelectedItem(null);
            jTextPaneObservacoes.setText("");

            jFormattedTextFieldDataCadastro.setEnabled(false);
            jTextFieldNome.setEnabled(false);
            jFormattedTextFieldDataNasc.setEnabled(false);
            jComboBoxSexo.setEnabled(false);
            jComboBoxEstadoCivil.setEnabled(false);
            jFormattedTextFieldRG.setEnabled(false);
            jFormattedTextFieldCPF.setEnabled(false);
            jFormattedTextFieldCTPS.setEnabled(false);
            jFormattedTextFieldSerie.setEnabled(false);
            jFormattedTextFieldPIS.setEnabled(false);
            jFormattedTextFieldTitulo.setEnabled(false);
            jFormattedTextFieldZona.setEnabled(false);
            jFormattedTextFieldSecao.setEnabled(false);
            jTextFieldEndereco.setEnabled(false);
            jTextFieldNumero.setEnabled(false);
            jTextFieldCidade.setEnabled(false);
            jTextFieldEstado.setEnabled(false);
            jFormattedTextFieldCEP.setEnabled(false);
            jTextFieldBairro.setEnabled(false);
            jFormattedTextFieldTelefone.setEnabled(false);
            jFormattedTextFieldCelular.setEnabled(false);
            jComboBoxCargo.setEnabled(false);
            jTextPaneObservacoes.setEnabled(false);

            jTextFieldPesquisaFuncionario.setEnabled(true);

            jButtonNovo.setEnabled(true);
            jButtonSalvar.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            jButtonPesquisar.setEnabled(true);
            preencherTabela("select *from funcionarios order by nome_funcionario");

            // FUNÇÃO ALTERAR DADOS

        }else{

            mod.setID(Integer.parseInt(jTextFieldIDFuncionario.getText()));
            mod.setDataCadastro(jFormattedTextFieldDataCadastro.getText());
            mod.setNome(jTextFieldNome.getText());
            mod.setDataNasc(jFormattedTextFieldDataNasc.getText());
            mod.setSexo((String)(jComboBoxSexo.getSelectedItem()));
            mod.setEstadoCivil((String)(jComboBoxEstadoCivil.getSelectedItem()));
            mod.setRG(jFormattedTextFieldRG.getText());
            mod.setCPF(jFormattedTextFieldCPF.getText());
            mod.setCTPS(Integer.parseInt(jFormattedTextFieldCTPS.getText()));
            mod.setSerie(jFormattedTextFieldSerie.getText());
            mod.setPIS(jFormattedTextFieldPIS.getText());
            mod.setTitulo(jFormattedTextFieldTitulo.getText());
            mod.setZona(Integer.parseInt(jFormattedTextFieldZona.getText()));
            mod.setSecao(Integer.parseInt(jFormattedTextFieldSecao.getText()));
            mod.setEndereco(jTextFieldEndereco.getText());
            mod.setNumero(Integer.parseInt(jTextFieldNumero.getText()));
            mod.setCidade(jTextFieldCidade.getText());
            mod.setEstado(jTextFieldEstado.getText());
            mod.setCEP(jFormattedTextFieldCEP.getText());
            mod.setBairro(jTextFieldBairro.getText());
            mod.setTelefone(jFormattedTextFieldTelefone.getText());
            mod.setCelular(jFormattedTextFieldCelular.getText());
            mod.setCargo((String)(jComboBoxCargo.getSelectedItem()));
            mod.setObs(jTextPaneObservacoes.getText());
            dao.Alterar(mod);

            jTextFieldIDFuncionario.setEnabled(false);
            jFormattedTextFieldDataCadastro.setEnabled(false);
            jTextFieldNome.setEnabled(false);
            jFormattedTextFieldDataNasc.setEnabled(false);
            jComboBoxSexo.setEnabled(false);
            jComboBoxEstadoCivil.setEnabled(false);
            jFormattedTextFieldRG.setEnabled(false);
            jFormattedTextFieldCPF.setEnabled(false);
            jFormattedTextFieldCTPS.setEnabled(false);
            jFormattedTextFieldSerie.setEnabled(false);
            jFormattedTextFieldPIS.setEnabled(false);
            jFormattedTextFieldTitulo.setEnabled(false);
            jFormattedTextFieldZona.setEnabled(false);
            jFormattedTextFieldSecao.setEnabled(false);
            jTextFieldEndereco.setEnabled(false);
            jTextFieldNumero.setEnabled(false);
            jTextFieldCidade.setEnabled(false);
            jTextFieldEstado.setEnabled(false);
            jFormattedTextFieldCEP.setEnabled(false);
            jTextFieldBairro.setEnabled(false);
            jFormattedTextFieldTelefone.setEnabled(false);
            jFormattedTextFieldCelular.setEnabled(false);
            jComboBoxCargo.setEnabled(false);
            jTextPaneObservacoes.setEnabled(false);
            jTextFieldPesquisaFuncionario.setEnabled(true);

            jTableFuncionarios.setVisible(true);

            jButtonNovo.setEnabled(true);
            jButtonSalvar.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            jButtonPesquisar.setEnabled(true);
            preencherTabela("select *from produtos order by descricao_produto");

        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModeloCadastro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModeloCadastro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModeloCadastro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModeloCadastro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModeloCadastro2 dialog = new ModeloCadastro2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxCargo;
    private javax.swing.JComboBox<String> jComboBoxEstadoCivil;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldCTPS;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelular;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataCadastro;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNasc;
    private javax.swing.JFormattedTextField jFormattedTextFieldPIS;
    private javax.swing.JFormattedTextField jFormattedTextFieldRG;
    private javax.swing.JFormattedTextField jFormattedTextFieldSecao;
    private javax.swing.JFormattedTextField jFormattedTextFieldSerie;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JFormattedTextField jFormattedTextFieldTitulo;
    private javax.swing.JFormattedTextField jFormattedTextFieldZona;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCTPS;
    private javax.swing.JLabel jLabelCargo;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelDataCadastro;
    private javax.swing.JLabel jLabelDataNasc;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelEstadoCivil;
    private javax.swing.JLabel jLabelIDFuncionario;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelObservacoes;
    private javax.swing.JLabel jLabelPIS;
    private javax.swing.JLabel jLabelPesquisarFuncionario;
    private javax.swing.JLabel jLabelRG;
    private javax.swing.JLabel jLabelSecao;
    private javax.swing.JLabel jLabelSerie;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelTituloEleitor;
    private javax.swing.JLabel jLabelZona;
    private javax.swing.JPanel jPanelCargo;
    private javax.swing.JPanel jPanelDadosCadastrais;
    private javax.swing.JPanel jPanelDadosPessoais;
    private javax.swing.JPanel jPanelEndereco;
    private javax.swing.JPanel jPanelPesquisar;
    private javax.swing.JPanel jPanelPesquisarFuncionarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPaneDadosCadastrais;
    private javax.swing.JTable jTableFuncionarios;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldIDFuncionario;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldPesquisaFuncionario;
    private javax.swing.JTextPane jTextPaneObservacoes;
    // End of variables declaration//GEN-END:variables
}
