
package Tela;

import CodigoInutlizado.CadastroClientes2;
import Conexao.ConexaoBD;
import ModeloBeans.BeansVendaCaixa;
import ModeloDao.DaoVendaCaixa;
import ModeloDao.PreencherTabela;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

public class VendaCaixa extends javax.swing.JDialog {
    CadastroClientes tela = new CadastroClientes();
    BeansVendaCaixa mod = new BeansVendaCaixa();
    DaoVendaCaixa addItem = new DaoVendaCaixa();
    ConexaoBD conecta = new ConexaoBD();
    //DefaultComboBoxModel dm = new DefaultComboBoxModel();
    int flag = 1;    
    int IDvenda;
    int QtdeItens;
    int itens;
    float PrecoProduto;
    //float Total = 0;
    float Total;
    private PesquisaClienteVenda pesquisarClientes;
    private PesquisarProdutos pesquisarProdutos;
    private ParcelamentoVenda parcelamento;
    
    private int IdVenda;
    private String Data;
    private float Valor;
    
    
    /**
     * Creates new form VendaCaixa
     */
    public VendaCaixa(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();        
        //preencherTabelaItensVenda("select *from itens_venda order by id_produto");
        preencherProdutos();
        this.pesquisarClientes = new PesquisaClienteVenda(this, true);     
        this.pesquisarProdutos = new PesquisarProdutos(this, true);    
        this.parcelamento = new ParcelamentoVenda(this, true);    
        jTextFieldQtdeItens.setText("0");
        //ArrayList<VendaCaixa> itens = new ArrayList<>();
        
        /*try{
            MaskFormatter form = new MaskFormatter("##/##/####");
            jFormattedTextFieldData.setFormatterFactory(new DefaultFormatterFactory(form));
            
        }catch (ParseException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher tabela!"); 
            
}  */
        //Pegar data do sistema
        
        SimpleDateFormat DF = new SimpleDateFormat("dd/MM/yyyy");
        Date hoje = new Date();
        jFormattedTextFieldData.setText(DF.format(hoje));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNomeCliente = new javax.swing.JLabel();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jButtonBuscarCliente = new javax.swing.JButton();
        jLabelProdutos = new javax.swing.JLabel();
        jLabelQtdeProdutos = new javax.swing.JLabel();
        jTextFieldQtdeProdutos = new javax.swing.JTextField();
        jLabelPrecoProduto = new javax.swing.JLabel();
        jTextFieldPrecoProduto = new javax.swing.JTextField();
        jLabelSubTotal = new javax.swing.JLabel();
        jTextFieldSubTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableItensVenda = new javax.swing.JTable();
        jButtonIncluir = new javax.swing.JButton();
        jTextFieldProduto = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabelData = new javax.swing.JLabel();
        jButtonBuscarProduto = new javax.swing.JButton();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jLabelIDProduto = new javax.swing.JLabel();
        jTextFieldIDProduto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldQtdeItens = new javax.swing.JTextField();
        jLabelTotal = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jButtonDesconto = new javax.swing.JButton();
        jButtonFinalizar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonConcluirDepois = new javax.swing.JButton();
        jButtonDeletarItem = new javax.swing.JButton();
        jTextFieldItem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxPagamento = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNomeCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNomeCliente.setForeground(new java.awt.Color(102, 102, 255));
        jLabelNomeCliente.setText("Cliente");

        jTextFieldNomeCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldNomeCliente.setForeground(new java.awt.Color(102, 102, 255));

        jButtonBuscarCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonBuscarCliente.setForeground(new java.awt.Color(102, 102, 255));
        jButtonBuscarCliente.setText("Buscar");
        jButtonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarClienteActionPerformed(evt);
            }
        });

        jLabelProdutos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelProdutos.setForeground(new java.awt.Color(102, 102, 255));
        jLabelProdutos.setText("Produto");

        jLabelQtdeProdutos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelQtdeProdutos.setForeground(new java.awt.Color(102, 102, 255));
        jLabelQtdeProdutos.setText("Qtde");

        jTextFieldQtdeProdutos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldQtdeProdutos.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldQtdeProdutos.setEnabled(false);
        jTextFieldQtdeProdutos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldQtdeProdutosFocusGained(evt);
            }
        });
        jTextFieldQtdeProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldQtdeProdutosKeyReleased(evt);
            }
        });

        jLabelPrecoProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPrecoProduto.setForeground(new java.awt.Color(102, 102, 255));
        jLabelPrecoProduto.setText("Preço");

        jTextFieldPrecoProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldPrecoProduto.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldPrecoProduto.setEnabled(false);

        jLabelSubTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSubTotal.setForeground(new java.awt.Color(102, 102, 255));
        jLabelSubTotal.setText("Total");

        jTextFieldSubTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldSubTotal.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldSubTotal.setEnabled(false);

        jTableItensVenda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableItensVenda.setForeground(new java.awt.Color(102, 102, 255));
        jTableItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableItensVenda.setEnabled(false);
        jTableItensVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableItensVendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableItensVenda);

        jButtonIncluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonIncluir.setForeground(new java.awt.Color(102, 102, 255));
        jButtonIncluir.setText("Incluir");
        jButtonIncluir.setEnabled(false);
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jTextFieldProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldProduto.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldProduto.setEnabled(false);

        jLabelID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelID.setForeground(new java.awt.Color(102, 102, 255));
        jLabelID.setText("ID Venda");

        jTextFieldID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldID.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldID.setEnabled(false);

        jLabelData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(102, 102, 255));
        jLabelData.setText("Data");

        jButtonBuscarProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonBuscarProduto.setForeground(new java.awt.Color(102, 102, 255));
        jButtonBuscarProduto.setText("Buscar");
        jButtonBuscarProduto.setEnabled(false);
        jButtonBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarProdutoActionPerformed(evt);
            }
        });

        jFormattedTextFieldData.setForeground(new java.awt.Color(102, 102, 255));
        jFormattedTextFieldData.setEnabled(false);
        jFormattedTextFieldData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabelIDProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelIDProduto.setForeground(new java.awt.Color(102, 102, 255));
        jLabelIDProduto.setText("ID");

        jTextFieldIDProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldIDProduto.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldIDProduto.setEnabled(false);
        jTextFieldIDProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelIDProduto)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldIDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelProdutos))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelData)
                                    .addComponent(jLabelID))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabelNomeCliente))
                                    .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBuscarProduto))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBuscarCliente)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldQtdeProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelQtdeProdutos))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPrecoProduto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonIncluir))
                            .addComponent(jLabelSubTotal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelData)
                            .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelID)
                                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNomeCliente)
                                    .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonBuscarCliente))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonBuscarProduto)
                                    .addComponent(jLabelIDProduto)
                                    .addComponent(jTextFieldIDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelProdutos)
                                    .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelPrecoProduto)
                                    .addComponent(jLabelQtdeProdutos))
                                .addGap(5, 5, 5)
                                .addComponent(jTextFieldPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldQtdeProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelSubTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonIncluir))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Qtde Itens");

        jTextFieldQtdeItens.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldQtdeItens.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldQtdeItens.setEnabled(false);

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTotal.setForeground(new java.awt.Color(255, 0, 0));
        jLabelTotal.setText("TOTAL");

        jTextFieldTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldTotal.setForeground(new java.awt.Color(255, 0, 0));
        jTextFieldTotal.setEnabled(false);

        jButtonDesconto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonDesconto.setForeground(new java.awt.Color(102, 102, 255));
        jButtonDesconto.setText("Desconto");
        jButtonDesconto.setEnabled(false);

        jButtonFinalizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonFinalizar.setForeground(new java.awt.Color(102, 102, 255));
        jButtonFinalizar.setText("Finalizar");
        jButtonFinalizar.setEnabled(false);
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(102, 102, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonConcluirDepois.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonConcluirDepois.setForeground(new java.awt.Color(102, 102, 255));
        jButtonConcluirDepois.setText("Concluir Depois");
        jButtonConcluirDepois.setEnabled(false);

        jButtonDeletarItem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonDeletarItem.setForeground(new java.awt.Color(102, 102, 255));
        jButtonDeletarItem.setText("Deletar Item");
        jButtonDeletarItem.setEnabled(false);
        jButtonDeletarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarItemActionPerformed(evt);
            }
        });

        jTextFieldItem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldItem.setForeground(new java.awt.Color(102, 102, 255));
        jTextFieldItem.setEnabled(false);
        jTextFieldItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Pagamento");

        jComboBoxPagamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxPagamento.setForeground(new java.awt.Color(102, 102, 255));
        jComboBoxPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A vista", "Parcelado" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDesconto)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFinalizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonConcluirDepois))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelTotal)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonDeletarItem)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldQtdeItens, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldQtdeItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeletarItem)
                    .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotal)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFinalizar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonConcluirDepois)
                    .addComponent(jButtonDesconto))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1035, 750));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        public void preencherProdutos() {
        conecta.conexao();
        conecta.executaSQL("select *from produtos order by descricao_produto");
        try {
            conecta.rs.first();
            //jComboBoxProdutos.removeAllItems();
            do{
                //jComboBoxProdutos.addItem(conecta.rs.getString("descricao_produto"));                
            }while(conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher a lista de Produtos!"+ex);
        }
        
        conecta.desconexao();
    
    }     
    
    public void preencherTabelaItensVenda(String Sql) {
        ArrayList dados = new ArrayList();
        String [] colunas = new String [] {"Qtde Itens","ID Prod.","Descrição","Qtde","Preço","Sub Total"}; 
        conecta.conexao();
        conecta.executaSQL(Sql);
        
        try{
            conecta.rs.first();
            do{
                float ValorProduto = conecta.rs.getFloat("precovenda_produto");
                int QtdVendida = conecta.rs.getInt("qtde_produto");
                //int QtdItens = conecta.rs.getInt("qtde_itens");
                dados.add(new Object[] {conecta.rs.getInt("qtde_itens"),conecta.rs.getInt("id_produto"),conecta.rs.getString("descricao_produto"),conecta.rs.getInt("qtde_produto"),conecta.rs.getFloat("precovenda_produto"), ValorProduto*QtdVendida});                
            }while(conecta.rs.next());                    
        }catch(SQLException ex) {
            
// Preenchendo a tabela
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher tabela!"+ex);   
        }
        PreencherTabela modelo = new PreencherTabela(dados, colunas);
        
        jTableItensVenda.setModel(modelo);        
        jTableItensVenda.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableItensVenda.getColumnModel().getColumn(0).setResizable(false);
        
        jTableItensVenda.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTableItensVenda.getColumnModel().getColumn(1).setResizable(false);
        
        jTableItensVenda.getColumnModel().getColumn(2).setPreferredWidth(400);
        jTableItensVenda.getColumnModel().getColumn(2).setResizable(false);
        
        jTableItensVenda.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTableItensVenda.getColumnModel().getColumn(3).setResizable(false);
        
        jTableItensVenda.getColumnModel().getColumn(4).setPreferredWidth(120);
        jTableItensVenda.getColumnModel().getColumn(4).setResizable(false);
                                           
        jTableItensVenda.getTableHeader().setReorderingAllowed(false);
        jTableItensVenda.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTableItensVenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);      
        SomaProdutos();
        conecta.desconexao();
    
    }    
         
    public void SomaProdutos () {
        Total = 0;
        int Qtde = 0;
        float valor = 0;
        conecta.executaSQL("select * from itens_venda inner join produtos on itens_venda.id_produto = produtos.id_produto where id_venda="+IDvenda);
        try {
            //conecta.rs.first();
            while(conecta.rs.next()) {
                Qtde = conecta.rs.getInt("qtde_produto");
                valor = conecta.rs.getFloat("precovenda_produto");
                Total = Total + conecta.rs.getFloat("precovenda_produto")*conecta.rs.getInt("qtde_produto");
            }
            jTextFieldTotal.setText(String.valueOf(Total));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao efetuar a soma do total da venda!!"+ ex);
        }
    }     
    
    public void SomaItens () {
        //nao esta funcionando ainda
        Total = 0;
        int Qtde = 0;
        int item = 0;
        conecta.executaSQL("select * from itens_venda inner join produtos on itens_venda.id_produto = produtos.id_produto where id_venda="+IDvenda);
        try {
            //conecta.rs.first();
            while(conecta.rs.next()) {
                Qtde = conecta.rs.getInt("qtde_produto");
                item = conecta.rs.getInt("qtde_itens");
                Total = Total + conecta.rs.getInt("qtde_produto")*conecta.rs.getInt("qtde_itens");
            }
            jTextFieldItem.setText(String.valueOf(Total));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao efetuar a soma dos itens da venda!!"+ ex);
        }
    }
    
    /*public void preencherItemVenda(String Sql) {
        ArrayList dados = new ArrayList();
        String [] colunas = new String [] {"ID Prod.","Descrição","Qtde","Preço","Sub Total"}; 
        conecta.conexao();
        conecta.executaSQL(Sql);
        
        try{
            conecta.rs.last();
            do{
                float ValorProduto = conecta.rs.getFloat("precovenda_produto");
                int QtdVendida = conecta.rs.getInt("qtde_produto");
                dados.remove(new Object[] {conecta.rs.getInt("id_produto"),conecta.rs.getString("descricao_produto"),conecta.rs.getInt("qtde_produto"),conecta.rs.getFloat("precovenda_produto"), ValorProduto*QtdVendida});                
            }while(conecta.rs.next());                    
        }catch(SQLException ex) {
            
// Preenchendo a tabela
            //JOptionPane.showMessageDialog(rootPane, "Erro ao preencher tabela!");   
        }
        PreencherTabela modelo = new PreencherTabela(dados, colunas);
        
        jTableItensVenda.setModel(modelo);        
        jTableItensVenda.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableItensVenda.getColumnModel().getColumn(0).setResizable(false);
        
        jTableItensVenda.getColumnModel().getColumn(1).setPreferredWidth(310);
        jTableItensVenda.getColumnModel().getColumn(1).setResizable(false);
        
        jTableItensVenda.getColumnModel().getColumn(2).setPreferredWidth(60);
        jTableItensVenda.getColumnModel().getColumn(2).setResizable(false);
        
        jTableItensVenda.getColumnModel().getColumn(3).setPreferredWidth(310);
        jTableItensVenda.getColumnModel().getColumn(3).setResizable(false);
        
        jTableItensVenda.getColumnModel().getColumn(4).setPreferredWidth(310);
        jTableItensVenda.getColumnModel().getColumn(4).setResizable(false);
                                           
        jTableItensVenda.getTableHeader().setReorderingAllowed(false);
        jTableItensVenda.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTableItensVenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);      
        
        conecta.desconexao();
        
    }*/
    
    private void jButtonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarClienteActionPerformed
        /*flag = 1;
        
        preencherTabelaCliente("select * from clientes where nome_cliente like'%"+jTextFieldNomeCliente.getText()+"%'");
        
        jTablePesquisa.setEnabled(true);
        jTextFieldNomeCliente.setText("");*/
          
        
        
        /*PesquisaClienteVenda DialogVenda = new PesquisaClienteVenda(new javax.swing.JDialog(),true); 
        DialogVenda.setVisible(true);*/
        
        conecta.conexao();
        try {
            PreparedStatement pst = conecta.Con.prepareStatement("insert into vendas (valor_venda)values (?)");
            pst.setFloat(1,0);
            pst.execute();
            
            conecta.executaSQL("select * from vendas");
            conecta.rs.last();
            IDvenda = conecta.rs.getInt("id_venda");
            
            jTextFieldID.setText(String.valueOf(conecta.rs.getInt("id_venda")));
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro!"+ ex);
        }
        
        this.pesquisarClientes.setVisible(true);
        this.jTextFieldNomeCliente.setText((this.pesquisarClientes.getCliente()));
        
        //jComboBoxProdutos.setEnabled(true);
        //jTextFieldQtdeProdutos.setEnabled(true);      
        jTextFieldProduto.setEnabled(true);
        jButtonBuscarProduto.setEnabled(true);
        
        
        
        
        
    }//GEN-LAST:event_jButtonBuscarClienteActionPerformed

    private void jButtonBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarProdutoActionPerformed
        this.pesquisarProdutos.setVisible(true);
        
        this.jTextFieldIDProduto.setText((this.pesquisarProdutos.getIdProduto()));
        this.jTextFieldProduto.setText((this.pesquisarProdutos.getProduto()));
        this.jTextFieldPrecoProduto.setText((this.pesquisarProdutos.getPrecoProduto()));
        this.jTextFieldSubTotal.setText((this.pesquisarProdutos.getPrecoProduto()));
        
        
        
        //jComboBoxProdutos.setEnabled(true);
        jTextFieldQtdeProdutos.setEnabled(true);
        jTextFieldQtdeProdutos.setText("1");
       
        jButtonIncluir.setEnabled(true);
        
    }//GEN-LAST:event_jButtonBuscarProdutoActionPerformed

    private void jTextFieldQtdeProdutosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQtdeProdutosKeyReleased
        float subTotal;
        subTotal = Float.valueOf(jTextFieldPrecoProduto.getText())*Integer.parseInt(jTextFieldQtdeProdutos.getText());
        jTextFieldSubTotal.setText(String.valueOf(subTotal));
    }//GEN-LAST:event_jTextFieldQtdeProdutosKeyReleased

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        try {
            int idvenda;
            int qtde = 0;           
            conecta.conexao();
            conecta.executaSQL("select * from produtos where descricao_produto='"+jTextFieldProduto.getText()+"'");
            conecta.rs.first();
            qtde = conecta.rs.getInt("qtdeatual_produto");
            if (qtde >= Integer.parseInt(jTextFieldQtdeProdutos.getText())) {    
                
            //mod.setQtdeItens(Integer.parseInt(jTextFieldIDProduto.getText()));    
            mod.setIdProduto(Integer.parseInt(jTextFieldIDProduto.getText()));    
            mod.setProduto(jTextFieldProduto.getText());
            mod.setQtdeProduto(Integer.parseInt(jTextFieldQtdeProdutos.getText()));
            mod.setPrecoProduto(Float.valueOf(jTextFieldPrecoProduto.getText()));
            mod.setTotalProduto(Float.valueOf(jTextFieldSubTotal.getText()));
            mod.setIdVenda(IDvenda);          
            
            //jTextFieldID.setText(String.valueOf(conecta.rs.getInt("id_venda")));           
                         
            addItem.AdicionaItem(mod);
            
            /*PreparedStatement pst = conecta.Con.prepareStatement("insert into itens_venda (qtde_itens)values (?)");
            pst.setFloat(1,1);
            pst.execute();
            
            conecta.executaSQL("select * from itens_venda");
            conecta.rs.last();
            IDvenda = conecta.rs.getInt("id_venda");*/
            
            //int resul = qtde - Integer.parseInt(jTextFieldQtdeProdutos.getText());
            preencherTabelaItensVenda("select * from produtos inner join itens_venda"
                    + " on produtos.id_produto = itens_venda.id_produto inner join vendas"
                    + " on vendas.id_venda = itens_venda.id_venda where vendas.id_venda="+IDvenda);
            
                     
            
            /*PreparedStatement pst = conecta.Con.prepareStatement("insert into itens_venda (qtde_itens)values (?)");
            pst.setInt(1,1);
            pst.execute();
            
            conecta.executaSQL("select * from itens_venda");
            conecta.rs.last();
            IDvenda = conecta.rs.getInt("id_venda");
            //QtdeItens = conecta.rs.getInt("qtde_itens");*/
            
            }else{
                JOptionPane.showMessageDialog(rootPane, "Não hã quantidade disponivel no estoque deste produto!");
            }
            
            //Total = Total + Float.parseFloat(jTextFieldPrecoProduto.getText())*Integer.parseInt(jTextFieldQtdeProdutos.getText());
            //jTextFieldTotal.setText(String.valueOf(Total));
            
            jTextFieldIDProduto.setText("");
            jTextFieldProduto.setText("");
            jTextFieldQtdeProdutos.setText("");
            jTextFieldPrecoProduto.setText("");
            jTextFieldSubTotal.setText("");
            
            
            //Inserindo quantidade de itens
            
            
            
            //jTextFieldID.setText(String.valueOf(conecta.rs.getInt("id_venda")));           
            
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(rootPane, "Erro ao pesquisar a quantidade!"+ ex);
        }
        
        jTableItensVenda.setEnabled(true);
        
        jButtonDeletarItem.setEnabled(true);
        jButtonDesconto.setEnabled(true);
        jButtonFinalizar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonConcluirDepois.setEnabled(true);
        
        
        
        
        
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jTextFieldQtdeProdutosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldQtdeProdutosFocusGained
        float subTotal;
        subTotal = Float.valueOf(jTextFieldPrecoProduto.getText())*Integer.parseInt(jTextFieldQtdeProdutos.getText());
        jTextFieldSubTotal.setText(String.valueOf(subTotal));
    }//GEN-LAST:event_jTextFieldQtdeProdutosFocusGained

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
        if(jComboBoxPagamento.getSelectedItem().equals("A vista")) {
        mod.setIdVenda(IDvenda);
        mod.setCliente(jTextFieldNomeCliente.getText());
        mod.setDataVenda(jFormattedTextFieldData.getText());
        mod.setValorVenda(Float.parseFloat(jTextFieldTotal.getText()));
        mod.setFormaPagto((String)jComboBoxPagamento.getSelectedItem());
        addItem.FinalizarVenda(mod);
        
        jTextFieldNomeCliente.setText("");        
        jTextFieldQtdeItens.setText("");
        jTextFieldTotal.setText("");
        
        jTextFieldProduto.setEnabled(false);
        jButtonBuscarProduto.setEnabled(false);
        jTextFieldQtdeProdutos.setEnabled(false);
        jButtonIncluir.setEnabled(false);
        //jTableItensVenda.setEnabled(false);
        jTableItensVenda.setVisible(false);
        jButtonDeletarItem.setEnabled(false);
        jButtonDesconto.setEnabled(false);
        jButtonFinalizar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonConcluirDepois.setEnabled(false);
        
        //dispose();
        }else {
        mod.setIdVenda(IDvenda);
        mod.setCliente(jTextFieldNomeCliente.getText());
        mod.setDataVenda(jFormattedTextFieldData.getText());
        mod.setValorVenda(Float.parseFloat(jTextFieldTotal.getText()));
        mod.setFormaPagto((String)jComboBoxPagamento.getSelectedItem());
        addItem.FinalizarVenda(mod);
        
        jTextFieldNomeCliente.setText("");        
        jTextFieldQtdeItens.setText("");
        jTextFieldTotal.setText("");
        
        jTextFieldProduto.setEnabled(false);
        jButtonBuscarProduto.setEnabled(false);
        jTextFieldQtdeProdutos.setEnabled(false);
        jButtonIncluir.setEnabled(false);
        //jTableItensVenda.setEnabled(false);
        jTableItensVenda.setVisible(false);
        jButtonDeletarItem.setEnabled(false);
        jButtonDesconto.setEnabled(false);
        jButtonFinalizar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonConcluirDepois.setEnabled(false);    
                
        this.parcelamento.setVisible(true);       
                      
        this.IdVenda = Integer.parseInt(this.jTextFieldID.getText());
        this.Data = (this.jFormattedTextFieldData.getText());
        this.Valor = Float.parseFloat(this.jTextFieldTotal.getText());
                  
        //ParcelamentoVenda frm = new ParcelamentoVenda(IDvenda);
        //this.jTextFieldNomeCliente.setText((this.pesquisarClientes.getCliente()));
            
        }
        
    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        addItem.CancelarVenda();
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonDeletarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarItemActionPerformed
        mod.setItemDeletado(Integer.parseInt(jTextFieldItem.getText()));
        addItem.ExcluirItem(mod);
        
        
        jTextFieldItem.setText("");
        
         //preencherTabelaItensVenda("select * from itens_venda inner join produtos on itens_venda.id_produto = produtos.id_produto where id_venda="+IDvenda);
         //preencherTabelaItensVenda("select * from itens_venda inner join produtos on itens_venda.id_produto = produtos.id_produto order by descricao_produto");         
            /*mod.setProduto(jTextFieldProduto.getText());
            mod.setQtdeProduto(Integer.parseInt(jTextFieldQtdeProdutos.getText()));
            mod.setPrecoProduto(Float.valueOf(jTextFieldPrecoProduto.getText()));
            mod.setTotalProduto(Float.valueOf(jTextFieldSubTotal.getText()));
            mod.setIdVenda(IDvenda);*/
            
            //mod.setIdProduto(Integer.parseInt(jTextFieldIDProduto.getText()));
            //mod.setQtdeItens(Integer.parseInt(jTextFieldItem.getText()));
            //addItem.ExcluirItem(mod);
            
            //addItem.ExcluirItem(mod);
            
            //addItem.DeletarItemVenda();
            
            /*preencherItemVenda("select * from produtos inner join itens_venda"
                    + " on produtos.id_produto = itens_venda.id_produto inner join vendas"
                    + " on vendas.id_venda = itens_venda.id_venda where vendas.id_venda="+IDvenda);*/
            
            
            /*Total = Total + Float.parseFloat(jTextFieldPrecoProduto.getText())*Integer.parseInt(jTextFieldQtdeProdutos.getText());
            jTextFieldTotal.setText(String.valueOf(Total));
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao pesquisar a quantidade!"+ ex);  
            
        }   */
            
            //System.out.println("linha selecionada "+jTableItensVenda.getSelectedRow());
            
        
        
        
            
    }//GEN-LAST:event_jButtonDeletarItemActionPerformed

    private void jTableItensVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableItensVendaMouseClicked
        String id_produto = "" + jTableItensVenda.getValueAt(jTableItensVenda.getSelectedRow(), 1);
        conecta.conexao();
        conecta.executaSQL("select *from itens_venda where id_produto = '"+ id_produto + "'");
        try {
        conecta.rs.first();
        jTextFieldItem.setText(String.valueOf(conecta.rs.getInt("id_produto")));
         }catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Erro ao selecionar item!"+ex);
        }
        
    }//GEN-LAST:event_jTableItensVendaMouseClicked

    private void jTextFieldIDProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDProdutoActionPerformed

    private void jTextFieldItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItemActionPerformed

     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VendaCaixa dialog = new VendaCaixa(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JButton jButtonBuscarProduto;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConcluirDepois;
    private javax.swing.JButton jButtonDeletarItem;
    private javax.swing.JButton jButtonDesconto;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JComboBox<String> jComboBoxPagamento;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelIDProduto;
    private javax.swing.JLabel jLabelNomeCliente;
    private javax.swing.JLabel jLabelPrecoProduto;
    private javax.swing.JLabel jLabelProdutos;
    private javax.swing.JLabel jLabelQtdeProdutos;
    private javax.swing.JLabel jLabelSubTotal;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableItensVenda;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldIDProduto;
    private javax.swing.JTextField jTextFieldItem;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldPrecoProduto;
    private javax.swing.JTextField jTextFieldProduto;
    private javax.swing.JTextField jTextFieldQtdeItens;
    private javax.swing.JTextField jTextFieldQtdeProdutos;
    private javax.swing.JTextField jTextFieldSubTotal;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables

    public int getIdVenda() {
        return IdVenda;
    }

    public void setIdVenda(int IdVenda) {
        this.IdVenda = IdVenda;
    }

    public String getData() {
        return Data;
    }

    public void setData(String Data) {
        this.Data = Data;
    }

    public float getValor() {
        return Valor;
    }

    public void setValor(float Valor) {
        this.Valor = Valor;
    }

    
    
    }
    
    /*public void recebendo(String recebe) {
        jTextFieldNomeCliente.setText(recebe);
    }*/
    
    
    
    

